import type { EnrichmentStationStatus } from '@/types/api';
import { Stat } from './AdminMetrics';
import { formatAge, formatProgress, formatUnknown } from './adminFormat';

export function AdminEnrichmentStatusPanel({
  hasToken,
  status,
  loading,
  error,
}: {
  hasToken: boolean;
  status: EnrichmentStationStatus | null;
  loading: boolean;
  error: string | null;
}) {
  if (!hasToken) {
    return (
      <p className="text-[11px] text-silver-dk font-mono">
        Set an admin token to view read-only enrichment status.
      </p>
    );
  }

  if (error) {
    return (
      <div className="panel-thin border-red/50 p-2 font-mono text-xs text-red" style={{ background: 'rgba(248,113,113,0.10)' }}>
        {error}
      </div>
    );
  }

  if (!status) {
    return (
      <p className="text-[11px] text-silver-dk font-mono">
        {loading ? 'Loading enrichment status...' : 'Enrichment status has not loaded yet.'}
      </p>
    );
  }

  if (!status.available) {
    return (
      <div className="space-y-2">
        <div className="panel-thin border-gold/45 p-3 font-mono text-xs text-gold" style={{ background: 'rgba(250,204,21,0.08)' }}>
          {status.message}
        </div>
        <p className="text-[10px] leading-snug text-silver-dk font-mono">
          The API reads a configured JSON artifact generated by the station enrichment status helper. It does not run enrichment, Docker, EDSM, or database work from this page.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs font-mono">
        <Stat label="Status" value={status.state} highlight={status.state === 'failed' || status.state === 'rate_limited'} />
        <Stat label="Checkpointed systems" value={formatUnknown(status.checkpoint?.processed_count)} />
        <Stat label="Last checkpointed id64" value={formatUnknown(status.checkpoint?.last_system_id64)} />
        <Stat label="Latest batch" value={formatUnknown(status.latest_batch?.number)} />
        <Stat label="Batch state" value={formatUnknown(status.latest_batch?.state)} highlight={status.latest_batch?.state === 'failed'} />
        <Stat label="Latest phase" value={formatUnknown(status.latest_batch?.latest_phase_name)} />
        <Stat label="Processed in report" value={formatUnknown(status.latest_report?.systems_processed)} />
        <Stat label="Fetch failures" value={formatUnknown(status.latest_report?.systems_fetch_failed ?? status.latest_progress?.systems_fetch_failed)} highlight={(status.latest_report?.systems_fetch_failed ?? 0) > 0} />
        <Stat label="Fetch errors" value={formatUnknown(status.latest_report?.fetch_errors ?? status.latest_progress?.fetch_errors)} highlight={(status.latest_report?.fetch_errors ?? 0) > 0} />
        <Stat label="Safety conflicts" value={formatUnknown(status.latest_report?.conflicts)} highlight={(status.latest_report?.conflicts ?? 0) > 0} />
        <Stat label="Rate-limit lines" value={formatUnknown(status.rate_limit?.recent_429_lines)} highlight={Boolean(status.rate_limit?.repeated_429_detected)} />
        <Stat label="Progress" value={formatProgress(status)} />
      </div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 text-xs font-mono">
        <Stat label="Status artifact" value={status.artifact?.file_name ?? 'hidden'} />
        <Stat label="Artifact age" value={formatAge(status.artifact?.age_seconds)} />
        <Stat label="Output dir" value={status.latest_run?.latest_all_records_output_dir_name ?? status.latest_run?.output_dir_name ?? '—'} />
        <Stat label="Latest report" value={status.latest_batch?.latest_report_file_name ?? '—'} />
        <Stat label="Latest stderr" value={status.latest_batch?.latest_stderr_file_name ?? '—'} />
        <Stat label="Latest log" value={status.latest_run?.latest_log_file_name ?? '—'} />
      </div>

      {status.warnings.length > 0 && (
        <div className="panel-thin border-gold/45 p-3 font-mono text-[11px] leading-snug text-gold" style={{ background: 'rgba(250,204,21,0.08)' }}>
          {status.warnings.slice(0, 3).map((warning) => (
            <div key={warning}>{warning}</div>
          ))}
        </div>
      )}

      <p className="text-[10px] leading-snug text-silver-dk font-mono">
        Read-only status from sanitized JSON. Full filesystem paths are hidden; missing values stay unavailable.
        {loading && <span className="text-orange-lt ml-2">refreshing...</span>}
      </p>
    </div>
  );
}
