packages:
  - .

allowBuilds:
  cypress: true

blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@csstools/css-color-parser@4.2.2'
  - '@csstools/css-syntax-patches-for-csstree@1.1.12'
  - '@internationalized/date@3.12.4'
  - '@lucide/svelte@1.37.0'
  - '@oxc-project/types@0.148.0'
  - '@rolldown/binding-android-arm-eabi@1.2.7'
  - '@rolldown/binding-android-arm64@1.2.7'
  - '@rolldown/binding-darwin-arm64@1.2.7'
  - '@rolldown/binding-darwin-x64@1.2.7'
  - '@rolldown/binding-freebsd-x64@1.2.7'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.7'
  - '@rolldown/binding-linux-arm64-gnu@1.2.7'
  - '@rolldown/binding-linux-arm64-musl@1.2.7'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.7'
  - '@rolldown/binding-linux-s390x-gnu@1.2.7'
  - '@rolldown/binding-linux-x64-gnu@1.2.7'
  - '@rolldown/binding-linux-x64-musl@1.2.7'
  - '@rolldown/binding-openharmony-arm64@1.2.7'
  - '@rolldown/binding-win32-arm64-msvc@1.2.7'
  - '@rolldown/binding-win32-x64-msvc@1.2.7'
  - '@typescript-eslint/eslint-plugin@8.69.0'
  - '@typescript-eslint/parser@8.69.0'
  - '@typescript-eslint/project-service@8.69.0'
  - '@typescript-eslint/scope-manager@8.69.0'
  - '@typescript-eslint/tsconfig-utils@8.69.0'
  - '@typescript-eslint/type-utils@8.69.0'
  - '@typescript-eslint/types@8.69.0'
  - '@typescript-eslint/typescript-estree@8.69.0'
  - '@typescript-eslint/utils@8.69.0'
  - '@typescript-eslint/visitor-keys@8.69.0'
  - 'ignore@7.0.8'
  - 'qs@6.16.0'
  - 'rc9@3.1.0'
  - 'rolldown@1.2.7'
  - 'systeminformation@5.33.8'
  - 'typescript-eslint@8.69.0'
  - 'zimmerframe@1.1.5'
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar@4.0.3'
