/** Typed same-origin bootstrap client. Types are generated by pinned Hey API. */
import type { AuthSessionResponse, HealthResponse } from './generated';

async function getJson<T>(path: string, signal?: AbortSignal): Promise<T> {
  const response = await fetch(path, { credentials: 'same-origin', signal });
  if (!response.ok) throw new Error(`Request failed (${response.status})`);
  return response.json() as Promise<T>;
}

export const getHealth = (signal?: AbortSignal) => getJson<HealthResponse>('/api/health', signal);
export const getAuthSession = (signal?: AbortSignal) =>
  getJson<AuthSessionResponse>('/api/auth/session', signal);
