/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/s/{id64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Share Stop Page
         * @description Bots → static HTML with OG/Twitter meta tags pointing at the PNG
         *     endpoint below. Real users → 302 to the SPA's `#s={id64}` deep-link
         *     so the existing client-side router takes over.
         */
        get: operations["share_stop_page_s__id64__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share/og/{id64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Og Image
         * @description Render a 1200×630 PNG preview card for the given system. Cached in
         *     Redis for 7 days; falls through to live render if cache is missing.
         */
        get: operations["og_image_api_share_og__id64__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Cheap, bounded liveness probe.
         *
         *     Bounded at 2 s with `asyncio.wait_for` so a wedged pool (every
         *     connection held by a slow query) cannot hang the healthcheck for
         *     the asyncpg `command_timeout` of 5 minutes. nginx's
         *     `proxy_read_timeout` on /api/health is 300s and Cloudflare's edge
         *     timeout is ~100s, so an unbounded probe means CF returns its own
         *     524 to the user before nginx ever gives up — and the api container
         *     keeps showing (healthy) to Docker's own healthcheck because that
         *     runs from inside the container against localhost without going
         *     through any of those timeouts.
         *
         *     Capping the probe at 2 s makes /api/health honest about pool
         *     exhaustion: if no connection is acquirable inside that window, we
         *     return 503 with a clear message and Docker can mark the container
         *     unhealthy and restart it, breaking the wedge.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local Status */
        get: operations["local_status_api_local_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/watchlist/{sync_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_v2_watchlist__sync_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/watchlist/{sync_key}/{id64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Watchlist */
        post: operations["add_watchlist_api_v2_watchlist__sync_key___id64__post"];
        /** Remove Watchlist */
        delete: operations["remove_watchlist_api_v2_watchlist__sync_key___id64__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/watchlist/{sync_key}/{id64}/alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Alert */
        patch: operations["update_alert_api_v2_watchlist__sync_key___id64__alert_patch"];
        trace?: never;
    };
    "/api/v2/watchlist/{sync_key}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watchlist Changes
         * @description Changes for systems currently in this sync_key's watchlist.
         */
        get: operations["watchlist_changes_api_v2_watchlist__sync_key__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Get */
        get: operations["legacy_get_api_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{id64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Legacy Post */
        post: operations["legacy_post_api_watchlist__id64__post"];
        /** Legacy Delete */
        delete: operations["legacy_delete_api_watchlist__id64__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{id64}/alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Legacy Patch */
        patch: operations["legacy_patch_api_watchlist__id64__alert_patch"];
        trace?: never;
    };
    "/api/watchlist/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Changes */
        get: operations["legacy_changes_api_watchlist_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/changelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Changelog */
        get: operations["legacy_changelog_api_watchlist_changelog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/systems/{sync_key}/{id64}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Note */
        get: operations["get_note_api_v2_systems__sync_key___id64__note_get"];
        put?: never;
        /** Save Note */
        post: operations["save_note_api_v2_systems__sync_key___id64__note_post"];
        /** Delete Note */
        delete: operations["delete_note_api_v2_systems__sync_key___id64__note_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/systems/{sync_key}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Notes
         * @description All notes for a single sync_key — used by the v2 frontend's
         *     'My Notes' tab.
         */
        get: operations["list_all_notes_api_v2_systems__sync_key__notes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/{id64}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legacy Get */
        get: operations["legacy_get_api_systems__id64__note_get"];
        put?: never;
        /** Legacy Post */
        post: operations["legacy_post_api_systems__id64__note_post"];
        /** Legacy Delete */
        delete: operations["legacy_delete_api_systems__id64__note_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/sync/{sync_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Sync */
        get: operations["get_profile_sync_api_profile_sync__sync_key__get"];
        /** Put Profile Sync */
        put: operations["put_profile_sync_api_profile_sync__sync_key__put"];
        post?: never;
        /**
         * Delete Profile Sync
         * @description Wipe a sync slot. Safe to call when the slot doesn't exist.
         */
        delete: operations["delete_profile_sync_api_profile_sync__sync_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cache Stats */
        get: operations["cache_stats_api_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cache Clear
         * @description Flush ED Finder cache keys + expired api_cache rows. X-Admin-Token required.
         *
         *     Audit fix (2026-05-08, AUDIT_REPORT.md §L9): previously this called
         *     `redis.flushdb()` which also wiped slowapi rate-limit keys, briefly
         *     disabling per-IP throttling right after a flush. Now we SCAN+DEL
         *     only the cache prefixes we own.
         */
        post: operations["cache_clear_api_cache_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rebuild-clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Rebuild Clusters
         * @description Kick a background cluster rebuild (dirty anchors only).
         *
         *     Returns 409 if a rebuild is already running. X-Admin-Token required.
         */
        post: operations["trigger_rebuild_clusters_api_admin_rebuild_clusters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rebuild-ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Rebuild Ratings
         * @description Recompute ratings for systems flagged as `rating_dirty`.
         *
         *     For the preview pod this runs synchronously on a tiny dataset
         *     (~40 systems). Production should swap in the real pipeline that
         *     walks bodies/stations and recomputes the per-economy scores.
         *     Rate-limited to 1/min and X-Admin-Token gated.
         */
        post: operations["trigger_rebuild_ratings_api_admin_rebuild_ratings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Events */
        get: operations["live_events_api_events_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Events */
        get: operations["recent_events_api_events_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete */
        get: operations["autocomplete_api_local_autocomplete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local Search Endpoint */
        post: operations["local_search_endpoint_api_local_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/galaxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Galaxy Search */
        post: operations["galaxy_search_api_search_galaxy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cluster Search */
        post: operations["cluster_search_api_search_cluster_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/{id64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System */
        get: operations["get_system_api_system__id64__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/local/system/{id64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local Get System */
        get: operations["local_get_system_api_local_system__id64__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/body/{body_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Body */
        get: operations["get_body_api_body__body_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systems/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Systems */
        post: operations["batch_systems_api_systems_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Regions
         * @description Return the 42 canonical ED galaxy regions with centroid coordinates
         *     (computed from the systems actually imported, so centres sit where the
         *     data is).
         */
        get: operations["map_regions_api_map_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/clusters/hulls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Cluster Hulls
         * @description Return cluster-anchor positions + approximate radius for map overlay.
         *
         *     Each cluster is summarised as:
         *       { anchor_id64, anchor_name, x, y, z, radius_ly, system_count,
         *         top_economy, top_score }
         *
         *     `radius_ly` is estimated from the best-known cluster's coverage (500 LY
         *     for standard cluster builder, 2000 LY for macro grid).  Cheap enough to
         *     compute on the fly and lets the frontend draw a translucent sphere
         *     without pulling per-member coordinates.
         */
        get: operations["map_cluster_hulls_api_map_clusters_hulls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Heatmap
         * @description Voxel-aggregated mean score for heatmap rendering.
         *
         *     Bins systems into `voxel_size` LY cubes, returns cells containing at
         *     least `min_systems` rated systems with their (x, y, z) centre and
         *     mean score. Keeps payload small enough for a full galaxy pull at
         *     200 LY voxels (≈ a few MB) while giving the frontend a spatial signal
         *     density map would never provide.
         */
        get: operations["map_heatmap_api_map_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Timeline
         * @description Return discovery-count time buckets for the EDDN time scrubber.
         *
         *     Powers the bonus "watch colonisation unfold" feature — a slider at the
         *     bottom of the map that filters to 'systems first scanned before
         *     <date>'.  Buckets by day/week/month/quarter/year.
         */
        get: operations["map_timeline_api_map_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ratings/rerank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ratings Rerank */
        post: operations["ratings_rerank_api_ratings_rerank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutocompleteHit */
        AutocompleteHit: {
            /** Id64 */
            id64: number;
            /** Name */
            name: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Z
             * @default 0
             */
            z: number;
            /**
             * Population
             * @default 0
             */
            population: number;
            /** Primaryeconomy */
            primaryEconomy?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** AutocompleteResponse */
        AutocompleteResponse: {
            /** Results */
            results: components["schemas"]["AutocompleteHit"][];
            /** Source */
            source?: string | null;
        };
        /**
         * BodyCountFilter
         * @description One body-count slider in `LocalSearchRequest.body_filters`. Each
         *     body-type key (`elw_count`, `ww_count`, …) maps to a min/max range,
         *     same shape as `RangeFilter` — duplicated here for naming clarity in
         *     the generated TS.
         */
        BodyCountFilter: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BodyFilters
         * @description `LocalSearchRequest.body_filters`. Keys mirror the
         *     `helpers.sys_row_to_dict` body-count column names. All optional —
         *     a missing key means "no filter on that body type".
         */
        BodyFilters: {
            elw_count?: components["schemas"]["BodyCountFilter"] | null;
            ww_count?: components["schemas"]["BodyCountFilter"] | null;
            ammonia_count?: components["schemas"]["BodyCountFilter"] | null;
            gas_giant_count?: components["schemas"]["BodyCountFilter"] | null;
            landable_count?: components["schemas"]["BodyCountFilter"] | null;
            terraformable_count?: components["schemas"]["BodyCountFilter"] | null;
            bio_signal_total?: components["schemas"]["BodyCountFilter"] | null;
            geo_signal_total?: components["schemas"]["BodyCountFilter"] | null;
            neutron_count?: components["schemas"]["BodyCountFilter"] | null;
            black_hole_count?: components["schemas"]["BodyCountFilter"] | null;
            white_dwarf_count?: components["schemas"]["BodyCountFilter"] | null;
            hmc_count?: components["schemas"]["BodyCountFilter"] | null;
            metal_rich_count?: components["schemas"]["BodyCountFilter"] | null;
            rocky_count?: components["schemas"]["BodyCountFilter"] | null;
            rocky_ice_count?: components["schemas"]["BodyCountFilter"] | null;
            icy_count?: components["schemas"]["BodyCountFilter"] | null;
            other_star_count?: components["schemas"]["BodyCountFilter"] | null;
            ring_count?: components["schemas"]["BodyCountFilter"] | null;
            walkable_count?: components["schemas"]["BodyCountFilter"] | null;
        } & {
            [key: string]: unknown;
        };
        /** BodyModel */
        BodyModel: {
            /** Id */
            id?: number | null;
            /** Name */
            name?: string | null;
            /** Subtype */
            subtype?: string | null;
            /** Body Type */
            body_type?: string | null;
            /** Distance From Star */
            distance_from_star?: number | null;
            /** Is Landable */
            is_landable?: boolean | null;
            /** Is Terraformable */
            is_terraformable?: boolean | null;
            /** Is Earth Like */
            is_earth_like?: boolean | null;
            /** Is Water World */
            is_water_world?: boolean | null;
            /** Is Ammonia World */
            is_ammonia_world?: boolean | null;
            /** Bio Signal Count */
            bio_signal_count?: number | null;
            /** Geo Signal Count */
            geo_signal_count?: number | null;
            /** Surface Temp */
            surface_temp?: number | null;
            /** Radius */
            radius?: number | null;
            /** Mass */
            mass?: number | null;
            /** Gravity */
            gravity?: number | null;
            /** Estimated Mapping Value */
            estimated_mapping_value?: number | null;
            /** Estimated Scan Value */
            estimated_scan_value?: number | null;
            /** Is Main Star */
            is_main_star?: boolean | null;
            /** Spectral Class */
            spectral_class?: string | null;
            /** Is Scoopable */
            is_scoopable?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** CacheStatsResponse */
        CacheStatsResponse: {
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Cache Misses
             * @default 0
             */
            cache_misses: number;
            /** Redis Hits */
            redis_hits?: number | null;
            /** Redis Misses */
            redis_misses?: number | null;
            /** Redis Memory Mb */
            redis_memory_mb?: number | null;
            /**
             * Db Cache Rows
             * @default 0
             */
            db_cache_rows: number;
        };
        /** ClusterRequirement */
        ClusterRequirement: {
            /**
             * Economy
             * @enum {string}
             */
            economy: "Agriculture" | "Refinery" | "Industrial" | "HighTech" | "Military" | "Tourism" | "Extraction";
            /**
             * Min Count
             * @default 1
             */
            min_count: number;
            /**
             * Min Score
             * @default 40
             */
            min_score: number;
        };
        /** ClusterSearchRequest */
        ClusterSearchRequest: {
            /** Requirements */
            requirements: components["schemas"]["ClusterRequirement"][];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            reference_coords?: components["schemas"]["CoordsModel"] | null;
        };
        /** CoordsModel */
        CoordsModel: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /** ExplorationValueModel */
        ExplorationValueModel: {
            /**
             * Total Scan Value
             * @default 0
             */
            total_scan_value: number;
            /**
             * Total Mapping Value
             * @default 0
             */
            total_mapping_value: number;
            /**
             * Combined Value
             * @default 0
             */
            combined_value: number;
        } & {
            [key: string]: unknown;
        };
        /** GalaxySearchRequest */
        GalaxySearchRequest: {
            /**
             * Economy
             * @default any
             */
            economy: "any" | ("Agriculture" | "Refinery" | "Industrial" | "HighTech" | "Military" | "Tourism" | "Extraction") | null;
            /**
             * Min Score
             * @default 0
             */
            min_score: number;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Version */
            version: string;
        };
        /** LocalSearchRequest */
        LocalSearchRequest: {
            filters?: components["schemas"]["SearchFilters"] | null;
            reference_coords?: components["schemas"]["CoordsModel"] | null;
            /**
             * Sort By
             * @default rating
             */
            sort_by: string | null;
            /**
             * Size
             * @default 50
             */
            size: number;
            /**
             * From
             * @default 0
             */
            from: number;
            body_filters?: components["schemas"]["BodyFilters"] | null;
            /** Require Bio */
            require_bio?: boolean | null;
            /** Require Geo */
            require_geo?: boolean | null;
            /** Require Terra */
            require_terra?: boolean | null;
            /** Star Types */
            star_types?: string[] | null;
            /** Min Rating */
            min_rating?: number | null;
            /**
             * Galaxy Wide
             * @default false
             */
            galaxy_wide: boolean;
        };
        /** NoteBody */
        NoteBody: {
            /** Note */
            note: string;
        };
        /**
         * ProfileSyncBlob
         * @description The shape is intentionally `Any` — the frontend owns the schema.
         *
         *     This is a pastebin slot; we don't validate sub-fields because the
         *     feature set evolves on the client and the backend shouldn't be a
         *     moving target every time we add a new tab.
         */
        ProfileSyncBlob: {
            /**
             * Blob
             * @description Arbitrary client-managed payload.
             */
            blob: unknown;
        };
        /**
         * RangeFilter
         * @description Inclusive numeric range used by `SearchFilters.distance` /
         *     `.population`. Either bound is optional — omit `min` for an upper-
         *     only filter, omit `max` for a lower-only one. (Frontend always
         *     sends both today; keep them optional so a future client can omit.)
         */
        RangeFilter: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RatingModel
         * @description camelCase rating block embedded inside SystemRow under `_rating`.
         *
         *     Mirrors the shape produced by `helpers.sys_row_to_dict` so the
         *     generated TypeScript matches what the search response actually puts
         *     on the wire.
         */
        RatingModel: {
            /** Score */
            score?: number | null;
            /** Scoreagriculture */
            scoreAgriculture?: number | null;
            /** Scorerefinery */
            scoreRefinery?: number | null;
            /** Scoreindustrial */
            scoreIndustrial?: number | null;
            /** Scorehightech */
            scoreHightech?: number | null;
            /** Scoremilitary */
            scoreMilitary?: number | null;
            /** Scoretourism */
            scoreTourism?: number | null;
            /** Scoreextraction */
            scoreExtraction?: number | null;
            /** Economysuggestion */
            economySuggestion?: string | null;
            /** Breakdown */
            breakdown?: unknown | null;
            /** Terraformingpotential */
            terraformingPotential?: number | null;
            /** Bodydiversity */
            bodyDiversity?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Rationale */
            rationale?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RerankRequest */
        RerankRequest: {
            /** Id64S */
            id64s: number[];
            weights?: components["schemas"]["RerankWeights"] | null;
            /** Economy */
            economy?: string | null;
        };
        /** RerankResponse */
        RerankResponse: {
            weights_applied: components["schemas"]["RerankWeights"];
            /** Economy Used */
            economy_used?: string | null;
            /** Results */
            results: components["schemas"]["RerankRow"][];
        };
        /** RerankRow */
        RerankRow: {
            /** Id64 */
            id64: number;
            /** Reranked Score */
            reranked_score: number;
            /** Original Score */
            original_score?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Rationale */
            rationale?: string | null;
            /** Economy Used */
            economy_used?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RerankWeights */
        RerankWeights: {
            /**
             * Economy
             * @default 0.42
             */
            economy: number;
            /**
             * Slots
             * @default 0.23
             */
            slots: number;
            /**
             * Strategic
             * @default 0.18
             */
            strategic: number;
            /**
             * Safety
             * @default 0.1
             */
            safety: number;
            /**
             * Terraforming
             * @default 0.05
             */
            terraforming: number;
            /**
             * Diversity
             * @default 0.02
             */
            diversity: number;
        };
        /** SearchFilters */
        SearchFilters: {
            distance?: components["schemas"]["RangeFilter"] | null;
            population?: components["schemas"]["RangeFilter"] | null;
            /** Economy */
            economy?: "any" | ("Agriculture" | "Refinery" | "Industrial" | "HighTech" | "Military" | "Tourism" | "Extraction") | null;
        };
        /**
         * SearchResponse
         * @description `/api/local/search` response.
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SystemRow"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Source */
            source?: string | null;
            /** Query Ms */
            query_ms?: number | null;
            /** Display Economy */
            display_economy?: string | null;
            /** Total Is Capped */
            total_is_capped?: boolean | null;
            /** Warning */
            warning?: string | null;
        };
        /** StationModel */
        StationModel: {
            /** Id */
            id?: number | null;
            /** Name */
            name?: string | null;
            /** Station Type */
            station_type?: string | null;
            /** Distance From Star */
            distance_from_star?: number | null;
            /** Landing Pad Size */
            landing_pad_size?: string | null;
            /** Has Market */
            has_market?: boolean | null;
            /** Has Shipyard */
            has_shipyard?: boolean | null;
            /** Has Outfitting */
            has_outfitting?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * StatusResponse
         * @description `/api/status` and `/api/local/status`.
         */
        StatusResponse: {
            /** Available */
            available: boolean;
            /**
             * Systems Count
             * @default 0
             */
            systems_count: number;
            /**
             * Body Count
             * @default 0
             */
            body_count: number;
            /**
             * Rated Count
             * @default 0
             */
            rated_count: number;
            /**
             * Clustered Count
             * @default 0
             */
            clustered_count: number;
            /**
             * Import Complete
             * @default false
             */
            import_complete: boolean;
            /**
             * Ratings Built
             * @default false
             */
            ratings_built: boolean;
            /**
             * Grid Built
             * @default false
             */
            grid_built: boolean;
            /**
             * Clusters Built
             * @default false
             */
            clusters_built: boolean;
            /**
             * Eddn Enabled
             * @default false
             */
            eddn_enabled: boolean;
            /**
             * Last Nightly Update
             * @default never
             */
            last_nightly_update: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Max Search Radius Ly
             * @default 500
             */
            max_search_radius_ly: number;
            /**
             * Has Body Data
             * @default false
             */
            has_body_data: boolean;
            /**
             * Version
             * @default
             */
            version: string;
            /** Backend */
            backend?: string | null;
            /** Pg Version */
            pg_version?: string | null;
            /** Station Count */
            station_count?: number | null;
            /** Cluster Count */
            cluster_count?: number | null;
            /** Grid Cells */
            grid_cells?: number | null;
            /** Macro Grid Cells */
            macro_grid_cells?: number | null;
            /** Galaxy Regions */
            galaxy_regions?: number | null;
            /** Db Size Mb */
            db_size_mb?: number | null;
            /** Import Status */
            import_status?: unknown | null;
            /** Cluster Radius Ly */
            cluster_radius_ly?: number | null;
            /** Has Cluster Summary */
            has_cluster_summary?: boolean | null;
            /** Has Bodies */
            has_bodies?: boolean | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * SystemDetailResponse
         * @description `/api/system/{id64}` response. Backend returns the same row
         *     twice under `record` and `system` for legacy compat.
         */
        SystemDetailResponse: {
            record: components["schemas"]["SystemDetailRow"];
            system: components["schemas"]["SystemDetailRow"];
        };
        /**
         * SystemDetailRow
         * @description Full system detail returned by `/api/system/{id64}`.
         *
         *     The detail endpoint does *not* go through the camelCase translator —
         *     it returns the joined ratings + bodies + stations rows snake_case
         *     as PostgreSQL emits them (see `routers/systems.py::get_system`).
         *     Frontend renders these strings directly.
         */
        SystemDetailRow: {
            /** Id64 */
            id64: number;
            /** Name */
            name: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Z
             * @default 0
             */
            z: number;
            /**
             * Population
             * @default 0
             */
            population: number;
            /** Primary Economy */
            primary_economy?: string | null;
            /** Secondary Economy */
            secondary_economy?: string | null;
            /** Security */
            security?: string | null;
            /** Allegiance */
            allegiance?: string | null;
            /** Government */
            government?: string | null;
            /** Is Colonised */
            is_colonised?: boolean | null;
            /** Main Star Type */
            main_star_type?: string | null;
            /** Main Star Subtype */
            main_star_subtype?: string | null;
            /** Score */
            score?: number | null;
            /** Score Agriculture */
            score_agriculture?: number | null;
            /** Score Refinery */
            score_refinery?: number | null;
            /** Score Industrial */
            score_industrial?: number | null;
            /** Score Hightech */
            score_hightech?: number | null;
            /** Score Military */
            score_military?: number | null;
            /** Score Tourism */
            score_tourism?: number | null;
            /** Score Extraction */
            score_extraction?: number | null;
            /** Economy Suggestion */
            economy_suggestion?: string | null;
            /** Elw Count */
            elw_count?: number | null;
            /** Ww Count */
            ww_count?: number | null;
            /** Ammonia Count */
            ammonia_count?: number | null;
            /** Gas Giant Count */
            gas_giant_count?: number | null;
            /** Landable Count */
            landable_count?: number | null;
            /** Terraformable Count */
            terraformable_count?: number | null;
            /** Bio Signal Total */
            bio_signal_total?: number | null;
            /** Geo Signal Total */
            geo_signal_total?: number | null;
            /** Neutron Count */
            neutron_count?: number | null;
            /** Black Hole Count */
            black_hole_count?: number | null;
            /** White Dwarf Count */
            white_dwarf_count?: number | null;
            /** Terraforming Potential */
            terraforming_potential?: number | null;
            /** Body Diversity */
            body_diversity?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Rationale */
            rationale?: string | null;
            /** Bodies */
            bodies?: components["schemas"]["BodyModel"][];
            /** Stations */
            stations?: components["schemas"]["StationModel"][];
            exploration_value?: components["schemas"]["ExplorationValueModel"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SystemRow
         * @description One result row inside `SearchResponse.results`.
         *
         *     Keep aligned with `helpers.sys_row_to_dict` (single source of truth
         *     for the camelCase translator).
         */
        SystemRow: {
            /** Id64 */
            id64: number;
            /**
             * Name
             * @default Unknown
             */
            name: string;
            coords?: components["schemas"]["CoordsModel"] | null;
            /** Distance */
            distance?: number | null;
            /**
             * Population
             * @default 0
             */
            population: number;
            /** Primaryeconomy */
            primaryEconomy?: string | null;
            /** Secondaryeconomy */
            secondaryEconomy?: string | null;
            /** Security */
            security?: string | null;
            /** Allegiance */
            allegiance?: string | null;
            /** Government */
            government?: string | null;
            /** Is Colonised */
            is_colonised?: boolean | null;
            /** Is Being Colonised */
            is_being_colonised?: boolean | null;
            /** Main Star Type */
            main_star_type?: string | null;
            /** Main Star Subtype */
            main_star_subtype?: string | null;
            _rating?: components["schemas"]["RatingModel"] | null;
            /** Elw Count */
            elw_count?: number | null;
            /** Ww Count */
            ww_count?: number | null;
            /** Ammonia Count */
            ammonia_count?: number | null;
            /** Gas Giant Count */
            gas_giant_count?: number | null;
            /** Landable Count */
            landable_count?: number | null;
            /** Terraformable Count */
            terraformable_count?: number | null;
            /** Bio Signal Total */
            bio_signal_total?: number | null;
            /** Geo Signal Total */
            geo_signal_total?: number | null;
            /** Neutron Count */
            neutron_count?: number | null;
            /** Black Hole Count */
            black_hole_count?: number | null;
            /** White Dwarf Count */
            white_dwarf_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistAlert */
        WatchlistAlert: {
            /** Min Score */
            min_score?: number | null;
            /** Economy */
            economy?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    share_stop_page_s__id64__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    og_image_api_share_og__id64__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    local_status_api_local_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_watchlist_api_v2_watchlist__sync_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_watchlist_api_v2_watchlist__sync_key___id64__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_watchlist_api_v2_watchlist__sync_key___id64__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_api_v2_watchlist__sync_key___id64__alert_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAlert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_changes_api_v2_watchlist__sync_key__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_get_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_post_api_watchlist__id64__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_delete_api_watchlist__id64__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_patch_api_watchlist__id64__alert_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAlert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_changes_api_watchlist_changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_changelog_api_watchlist_changelog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_note_api_v2_systems__sync_key___id64__note_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_note_api_v2_systems__sync_key___id64__note_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v2_systems__sync_key___id64__note_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_notes_api_v2_systems__sync_key__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_get_api_systems__id64__note_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_post_api_systems__id64__note_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_delete_api_systems__id64__note_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_sync_api_profile_sync__sync_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_sync_api_profile_sync__sync_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSyncBlob"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_sync_api_profile_sync__sync_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sync_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_stats_api_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStatsResponse"];
                };
            };
        };
    };
    cache_clear_api_cache_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_rebuild_clusters_api_admin_rebuild_clusters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_rebuild_ratings_api_admin_rebuild_ratings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    live_events_api_events_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    recent_events_api_events_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autocomplete_api_local_autocomplete_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_search_endpoint_api_local_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    galaxy_search_api_search_galaxy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GalaxySearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_search_api_search_cluster_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_api_system__id64__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_get_system_api_local_system__id64__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id64: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_body_api_body__body_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                body_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_systems_api_systems_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    map_regions_api_map_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    map_cluster_hulls_api_map_clusters_hulls_get: {
        parameters: {
            query?: {
                /** @description Minimum systems per cluster */
                min_count?: number;
                /** @description Cap on returned hulls */
                max_hulls?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_heatmap_api_map_heatmap_get: {
        parameters: {
            query?: {
                /** @description Voxel cell size in LY */
                voxel_size?: number;
                /** @description Minimum systems per voxel */
                min_systems?: number;
                /** @description Filter to a specific economy score */
                economy?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_timeline_api_map_timeline_get: {
        parameters: {
            query?: {
                bucket?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ratings_rerank_api_ratings_rerank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
