-- ED-Finder V3 migration 001: fresh PostgreSQL 18 baseline.
-- PRODUCTION-INTENDED SCHEMA SOURCE — NOT YET DEPLOYED.
--
-- This migration intentionally has no dependency on the V2 migration chain.
-- Required PostgreSQL extensions: none. In particular, PostGIS is not used.

BEGIN;

CREATE SCHEMA v3_source;
CREATE SCHEMA v3_vocab;
CREATE SCHEMA v3_identity;
CREATE SCHEMA v3_private;
CREATE SCHEMA v3_meta;
CREATE SCHEMA v3_async;

COMMENT ON SCHEMA v3_source IS 'V3 source acquisition, provenance, reconciliation evidence, and unmapped source vocabulary.';
COMMENT ON SCHEMA v3_vocab IS 'V3 governed public vocabulary. Internal smallint tokens are never public identity.';
COMMENT ON SCHEMA v3_identity IS 'V3 product accounts, Commanders, credentials, roles, and provider-scoped identities.';
COMMENT ON SCHEMA v3_private IS 'V3 private trust-zone imports/facts and explicit contribution/withdrawal receipts.';
COMMENT ON SCHEMA v3_meta IS 'V3 migration, canonical generation, relation-build, validation, and publication metadata.';
COMMENT ON SCHEMA v3_async IS 'V3 authoritative durable jobs, leases, attempts, chunks, outbox, and effect receipts.';

-- ---------------------------------------------------------------------------
-- Source/acquisition ledger (ADR-007, ADR-010, ADR-017)
-- ---------------------------------------------------------------------------

CREATE TABLE v3_source.source (
    source_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    endpoint_identity text,
    authority_class text NOT NULL CHECK (authority_class IN (
        'OPERATOR_ADJUDICATION', 'FRONTIER_DIRECT', 'PRIMARY_AGGREGATED',
        'SECONDARY_AGGREGATED', 'REFERENCE_CURATED', 'LEGACY_FALLBACK'
    )),
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CHECK (source_code ~ '^[a-z][a-z0-9_.-]{0,62}$')
);

COMMENT ON TABLE v3_source.source IS 'Source/endpoint identity only. Credentials and provider secrets are forbidden here.';

CREATE TABLE v3_source.source_rights_policy (
    rights_policy_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id smallint NOT NULL REFERENCES v3_source.source(source_id),
    policy_version text NOT NULL,
    rights_class text NOT NULL CHECK (rights_class IN (
        'PRIVATE_ONLY', 'INTERNAL_USE', 'SHAREABLE', 'CANONICAL_ELIGIBLE', 'QUARANTINED'
    )),
    retention_class text NOT NULL,
    distribution_allowed boolean NOT NULL DEFAULT false,
    policy_document_uri text,
    policy_sha256 bytea,
    effective_at timestamptz NOT NULL,
    retired_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE (source_id, policy_version),
    UNIQUE (rights_policy_id, source_id),
    CHECK (policy_sha256 IS NULL OR octet_length(policy_sha256) = 32),
    CHECK (retired_at IS NULL OR retired_at >= effective_at)
);

CREATE INDEX source_rights_policy_source_idx
    ON v3_source.source_rights_policy(source_id, effective_at DESC);
COMMENT ON INDEX v3_source.source_rights_policy_source_idx IS 'Use: resolve the effective rights policy for one source acquisition.';

CREATE TABLE v3_source.source_artifact (
    artifact_id uuid PRIMARY KEY,
    source_id smallint NOT NULL REFERENCES v3_source.source(source_id),
    rights_policy_id bigint NOT NULL,
    artifact_kind text NOT NULL,
    endpoint_identity text,
    content_sha256 bytea NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    media_type text NOT NULL,
    compression_code text,
    retrieved_at timestamptz NOT NULL,
    effective_at timestamptz,
    served_contract_sha256 bytea,
    served_contract_media_type text,
    retention_class text NOT NULL,
    quarantine_state text NOT NULL DEFAULT 'ADMITTED' CHECK (quarantine_state IN (
        'ADMITTED', 'QUARANTINED', 'REJECTED', 'WITHDRAWN'
    )),
    storage_locator text,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE (source_id, content_sha256),
    UNIQUE (artifact_id, source_id),
    FOREIGN KEY (rights_policy_id, source_id)
        REFERENCES v3_source.source_rights_policy(rights_policy_id, source_id),
    CHECK (octet_length(content_sha256) = 32),
    CHECK (served_contract_sha256 IS NULL OR octet_length(served_contract_sha256) = 32)
);

COMMENT ON TABLE v3_source.source_artifact IS 'Immutable acquisition artifact identity and served-contract hash; locators must not contain credentials.';
CREATE INDEX source_artifact_source_retrieved_idx
    ON v3_source.source_artifact(source_id, retrieved_at DESC);
COMMENT ON INDEX v3_source.source_artifact_source_retrieved_idx IS 'Use: list recent immutable artifacts for a source.';

CREATE TABLE v3_source.source_run (
    source_run_id uuid PRIMARY KEY,
    source_id smallint NOT NULL REFERENCES v3_source.source(source_id),
    rights_policy_id bigint NOT NULL,
    artifact_id uuid,
    retry_of_source_run_id uuid,
    acquisition_kind text NOT NULL CHECK (acquisition_kind IN (
        'BULK_SNAPSHOT', 'DELTA', 'STREAM_WINDOW', 'JOURNAL_IMPORT',
        'GOVERNED_RELEASE', 'OPERATOR_ADJUDICATION'
    )),
    trust_zone text NOT NULL CHECK (trust_zone IN ('PRIVATE', 'SHARED', 'CANONICAL')),
    run_state text NOT NULL CHECK (run_state IN (
        'PLANNED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'QUARANTINED', 'CANCELLED'
    )),
    idempotency_key text NOT NULL,
    coverage_domain text,
    scope_contract jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_complete_snapshot boolean NOT NULL DEFAULT false,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    effective_at timestamptz,
    importer_version text NOT NULL,
    importer_code_sha256 bytea NOT NULL,
    importer_config_sha256 bytea NOT NULL,
    normalizer_version text NOT NULL,
    normalizer_sha256 bytea NOT NULL,
    served_contract_sha256 bytea,
    failure_code text,
    failure_detail text,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE (source_id, idempotency_key),
    UNIQUE (source_run_id, source_id),
    FOREIGN KEY (rights_policy_id, source_id)
        REFERENCES v3_source.source_rights_policy(rights_policy_id, source_id),
    FOREIGN KEY (artifact_id, source_id)
        REFERENCES v3_source.source_artifact(artifact_id, source_id),
    FOREIGN KEY (retry_of_source_run_id, source_id)
        REFERENCES v3_source.source_run(source_run_id, source_id),
    CHECK (jsonb_typeof(scope_contract) = 'object'),
    CHECK (completed_at IS NULL OR completed_at >= started_at),
    CHECK (octet_length(importer_code_sha256) = 32),
    CHECK (octet_length(importer_config_sha256) = 32),
    CHECK (octet_length(normalizer_sha256) = 32),
    CHECK (served_contract_sha256 IS NULL OR octet_length(served_contract_sha256) = 32),
    CHECK ((run_state IN ('SUCCEEDED', 'PARTIAL', 'FAILED', 'QUARANTINED', 'CANCELLED')) = (completed_at IS NOT NULL))
);

CREATE INDEX source_run_source_started_idx
    ON v3_source.source_run(source_id, started_at DESC);
COMMENT ON INDEX v3_source.source_run_source_started_idx IS 'Use: source acquisition history and latest complete-snapshot reconciliation.';

CREATE TABLE v3_source.source_checkpoint (
    source_run_id uuid NOT NULL REFERENCES v3_source.source_run(source_run_id),
    chunk_key text NOT NULL,
    chunk_ordinal integer NOT NULL CHECK (chunk_ordinal >= 0),
    deterministic_identity_sha256 bytea NOT NULL,
    checkpoint_state text NOT NULL CHECK (checkpoint_state IN (
        'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'QUARANTINED'
    )),
    input_offset bigint,
    rows_read bigint NOT NULL DEFAULT 0 CHECK (rows_read >= 0),
    rows_accepted bigint NOT NULL DEFAULT 0 CHECK (rows_accepted >= 0),
    rows_rejected bigint NOT NULL DEFAULT 0 CHECK (rows_rejected >= 0),
    started_at timestamptz,
    completed_at timestamptz,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (source_run_id, chunk_key),
    UNIQUE (source_run_id, chunk_ordinal),
    UNIQUE (source_run_id, deterministic_identity_sha256),
    CHECK (octet_length(deterministic_identity_sha256) = 32),
    CHECK (jsonb_typeof(detail) = 'object'),
    CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE v3_source.source_rejection (
    source_rejection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_run_id uuid NOT NULL,
    chunk_key text,
    rejection_code text NOT NULL,
    entity_kind text,
    source_record_identity text,
    raw_payload_sha256 bytea,
    evidence_locator text,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    rejected_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    FOREIGN KEY (source_run_id) REFERENCES v3_source.source_run(source_run_id),
    FOREIGN KEY (source_run_id, chunk_key)
        REFERENCES v3_source.source_checkpoint(source_run_id, chunk_key),
    CHECK (raw_payload_sha256 IS NULL OR octet_length(raw_payload_sha256) = 32),
    CHECK (jsonb_typeof(detail) = 'object')
);

CREATE INDEX source_rejection_run_idx
    ON v3_source.source_rejection(source_run_id, rejected_at);
COMMENT ON INDEX v3_source.source_rejection_run_idx IS 'Use: review every rejected record for one acquisition attempt.';

CREATE TABLE v3_source.unmapped_vocabulary (
    unmapped_vocabulary_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_run_id uuid NOT NULL REFERENCES v3_source.source_run(source_run_id),
    vocabulary_domain text NOT NULL,
    raw_token text NOT NULL,
    normalized_candidate text,
    mapping_state text NOT NULL DEFAULT 'UNMAPPED' CHECK (mapping_state IN (
        'UNMAPPED', 'MAPPED', 'QUARANTINED', 'REJECTED'
    )),
    mapped_public_code text,
    first_observed_at timestamptz NOT NULL,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (source_run_id, vocabulary_domain, raw_token),
    CHECK (jsonb_typeof(detail) = 'object'),
    CHECK ((mapping_state = 'MAPPED') = (mapped_public_code IS NOT NULL))
);

-- ---------------------------------------------------------------------------
-- Governed vocabulary. External vocabularies are reference data, never enums.
-- ---------------------------------------------------------------------------

CREATE TABLE v3_vocab.galaxy_region (
    galaxy_region_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.body_type (
    body_type_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.atmosphere_classification (
    atmosphere_classification_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.terraforming_state (
    terraforming_state_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.volcanism_type (
    volcanism_type_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.ring_type (
    ring_type_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.reserve_type (
    reserve_type_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.signal_type (
    signal_type_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.genus (
    genus_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.station_type (
    station_type_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.station_service (
    station_service_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.economy (
    economy_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    display_name text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_vocab.identity_namespace (
    identity_namespace_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    entity_kind text NOT NULL CHECK (entity_kind IN ('BODY', 'RING', 'STATION')),
    active boolean NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------------
-- Accounts, Commanders, provider identities, credentials, and audit.
-- ---------------------------------------------------------------------------

CREATE TABLE v3_identity.account (
    account_id uuid PRIMARY KEY,
    account_state text NOT NULL DEFAULT 'ACTIVE' CHECK (account_state IN (
        'ACTIVE', 'SUSPENDED', 'CLOSED'
    )),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    closed_at timestamptz,
    CHECK ((account_state = 'CLOSED') = (closed_at IS NOT NULL))
);

CREATE TABLE v3_identity.external_identity (
    external_identity_id uuid PRIMARY KEY,
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    provider text NOT NULL,
    issuer text NOT NULL,
    subject text NOT NULL,
    verified_at timestamptz,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE (provider, issuer, subject)
);

CREATE INDEX external_identity_account_idx
    ON v3_identity.external_identity(account_id);
COMMENT ON INDEX v3_identity.external_identity_account_idx IS 'Use: list login-provider identities linked to one account.';

CREATE TABLE v3_identity.commander (
    commander_id uuid PRIMARY KEY,
    commander_name text NOT NULL,
    commander_state text NOT NULL DEFAULT 'ACTIVE' CHECK (commander_state IN (
        'ACTIVE', 'ARCHIVED'
    )),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp()
);

COMMENT ON COLUMN v3_identity.commander.commander_name IS 'Mutable and non-unique; never authentication or canonical identity.';

CREATE TABLE v3_identity.account_commander_access (
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    commander_id uuid NOT NULL REFERENCES v3_identity.commander(commander_id),
    access_role text NOT NULL CHECK (access_role IN ('OWNER', 'EDITOR', 'VIEWER')),
    granted_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    revoked_at timestamptz,
    PRIMARY KEY (account_id, commander_id)
);

CREATE UNIQUE INDEX account_commander_one_owner_uidx
    ON v3_identity.account_commander_access(commander_id)
    WHERE access_role = 'OWNER' AND revoked_at IS NULL;

CREATE TABLE v3_identity.commander_external_identity (
    commander_external_identity_id uuid PRIMARY KEY,
    commander_id uuid NOT NULL REFERENCES v3_identity.commander(commander_id),
    provider text NOT NULL,
    issuer text NOT NULL,
    subject text NOT NULL,
    verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE (provider, issuer, subject)
);

CREATE INDEX commander_external_identity_commander_idx
    ON v3_identity.commander_external_identity(commander_id);
COMMENT ON INDEX v3_identity.commander_external_identity_commander_idx IS 'Use: list game/provider identities linked to one Commander.';

CREATE TABLE v3_identity.role (
    role_id smallint PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    description text NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE v3_identity.account_role (
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    role_id smallint NOT NULL REFERENCES v3_identity.role(role_id),
    granted_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    revoked_at timestamptz,
    PRIMARY KEY (account_id, role_id)
);

CREATE TABLE v3_identity.device_credential (
    device_credential_id uuid PRIMARY KEY,
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    credential_kind text NOT NULL,
    public_key bytea NOT NULL,
    signature_counter bigint NOT NULL DEFAULT 0 CHECK (signature_counter >= 0),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    last_used_at timestamptz,
    revoked_at timestamptz
);

CREATE INDEX device_credential_account_idx
    ON v3_identity.device_credential(account_id)
    WHERE revoked_at IS NULL;
COMMENT ON INDEX v3_identity.device_credential_account_idx IS 'Use: list active device credentials for one account.';

CREATE TABLE v3_identity.session (
    session_id uuid PRIMARY KEY,
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    device_credential_id uuid REFERENCES v3_identity.device_credential(device_credential_id),
    session_token_sha256 bytea NOT NULL UNIQUE,
    session_state text NOT NULL DEFAULT 'ACTIVE' CHECK (session_state IN (
        'ACTIVE', 'ROTATED', 'REVOKED'
    )),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    last_seen_at timestamptz NOT NULL,
    idle_expires_at timestamptz NOT NULL,
    absolute_expires_at timestamptz NOT NULL,
    last_authenticated_at timestamptz NOT NULL,
    recent_auth_expires_at timestamptz NOT NULL,
    rotation_counter bigint NOT NULL DEFAULT 0 CHECK (rotation_counter >= 0),
    rotated_to_session_id uuid,
    rotated_at timestamptz,
    revoked_at timestamptz,
    UNIQUE (session_id, account_id),
    FOREIGN KEY (rotated_to_session_id, account_id)
        REFERENCES v3_identity.session(session_id, account_id),
    CHECK (octet_length(session_token_sha256) = 32),
    CHECK (last_seen_at >= created_at),
    CHECK (idle_expires_at > last_seen_at),
    CHECK (absolute_expires_at > created_at),
    CHECK (idle_expires_at <= absolute_expires_at),
    CHECK (last_authenticated_at >= created_at),
    CHECK (recent_auth_expires_at > last_authenticated_at),
    CHECK (recent_auth_expires_at <= absolute_expires_at),
    CHECK ((session_state = 'ROTATED') =
        (rotated_to_session_id IS NOT NULL AND rotated_at IS NOT NULL)),
    CHECK ((session_state = 'REVOKED') = (revoked_at IS NOT NULL)),
    CHECK (rotated_at IS NULL OR rotated_at >= created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX session_account_active_idx
    ON v3_identity.session(account_id, idle_expires_at, absolute_expires_at)
    WHERE session_state = 'ACTIVE';
COMMENT ON INDEX v3_identity.session_account_active_idx IS 'Use: authorize active sessions against both idle and absolute expiry.';

CREATE TABLE v3_identity.personal_data_request (
    personal_data_request_id uuid PRIMARY KEY,
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    request_kind text NOT NULL CHECK (request_kind IN ('EXPORT', 'DELETE')),
    request_state text NOT NULL DEFAULT 'REQUESTED' CHECK (request_state IN (
        'REQUESTED', 'IDENTITY_VERIFIED', 'PROCESSING', 'COMPLETED',
        'REJECTED', 'CANCELLED'
    )),
    idempotency_key text NOT NULL,
    requested_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    identity_verified_at timestamptz,
    due_at timestamptz,
    completed_at timestamptz,
    processing_job_id uuid,
    scope jsonb NOT NULL,
    result_sha256 bytea,
    result_locator text,
    receipt jsonb,
    failure_code text,
    UNIQUE (account_id, request_kind, idempotency_key),
    CHECK (jsonb_typeof(scope) = 'object'),
    CHECK (receipt IS NULL OR jsonb_typeof(receipt) = 'object'),
    CHECK (result_sha256 IS NULL OR octet_length(result_sha256) = 32),
    CHECK (identity_verified_at IS NULL OR identity_verified_at >= requested_at),
    CHECK (due_at IS NULL OR due_at >= requested_at),
    CHECK (completed_at IS NULL OR completed_at >= requested_at),
    CHECK ((request_state = 'COMPLETED') = (completed_at IS NOT NULL))
);

CREATE INDEX personal_data_request_account_time_idx
    ON v3_identity.personal_data_request(account_id, requested_at DESC);
COMMENT ON INDEX v3_identity.personal_data_request_account_time_idx IS 'Use: audit one account export/delete request history and outcome receipts.';

CREATE TABLE v3_identity.service_principal (
    service_principal_id uuid PRIMARY KEY,
    public_code text NOT NULL UNIQUE,
    principal_state text NOT NULL DEFAULT 'ACTIVE' CHECK (principal_state IN (
        'ACTIVE', 'SUSPENDED', 'RETIRED'
    )),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    retired_at timestamptz
);

CREATE TABLE v3_identity.service_principal_credential (
    service_principal_credential_id uuid PRIMARY KEY,
    service_principal_id uuid NOT NULL REFERENCES v3_identity.service_principal(service_principal_id),
    credential_sha256 bytea NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    expires_at timestamptz,
    revoked_at timestamptz,
    CHECK (octet_length(credential_sha256) = 32)
);

CREATE TABLE v3_identity.security_audit_event (
    security_audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    account_id uuid REFERENCES v3_identity.account(account_id),
    service_principal_id uuid REFERENCES v3_identity.service_principal(service_principal_id),
    event_code text NOT NULL,
    subject_reference text,
    outcome text NOT NULL CHECK (outcome IN ('SUCCEEDED', 'DENIED', 'FAILED')),
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (jsonb_typeof(detail) = 'object'),
    CHECK (account_id IS NOT NULL OR service_principal_id IS NOT NULL)
);

CREATE INDEX security_audit_event_account_time_idx
    ON v3_identity.security_audit_event(account_id, occurred_at DESC)
    WHERE account_id IS NOT NULL;
COMMENT ON INDEX v3_identity.security_audit_event_account_time_idx IS 'Use: account security history review.';

CREATE TABLE v3_identity.legacy_sync_claim (
    legacy_sync_claim_id uuid PRIMARY KEY,
    sync_key_sha256 bytea NOT NULL UNIQUE,
    account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    commander_id uuid REFERENCES v3_identity.commander(commander_id),
    claim_state text NOT NULL CHECK (claim_state IN (
        'PENDING', 'CLAIMED', 'REJECTED', 'REVOKED'
    )),
    claimed_at timestamptz,
    revoked_at timestamptz,
    CHECK (octet_length(sync_key_sha256) = 32)
);

COMMENT ON TABLE v3_identity.legacy_sync_claim IS 'Claim-only V2 migration boundary. A sync key is never V3 authentication, authorization, ownership, or identity.';

-- ---------------------------------------------------------------------------
-- Private trust-zone ownership and explicit sharing/withdrawal boundary.
-- ---------------------------------------------------------------------------

CREATE TABLE v3_private.private_import (
    private_import_id uuid PRIMARY KEY,
    owner_account_id uuid NOT NULL REFERENCES v3_identity.account(account_id),
    owner_commander_id uuid,
    source_run_id uuid NOT NULL REFERENCES v3_source.source_run(source_run_id),
    artifact_id uuid REFERENCES v3_source.source_artifact(artifact_id),
    import_kind text NOT NULL,
    import_state text NOT NULL CHECK (import_state IN (
        'RECEIVED', 'VALIDATING', 'READY', 'REJECTED', 'WITHDRAWN'
    )),
    imported_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    withdrawn_at timestamptz,
    withdrawal_reason text,
    FOREIGN KEY (owner_account_id, owner_commander_id)
        REFERENCES v3_identity.account_commander_access(account_id, commander_id),
    UNIQUE (private_import_id, owner_account_id),
    CHECK ((import_state = 'WITHDRAWN') = (withdrawn_at IS NOT NULL))
);

CREATE INDEX private_import_owner_time_idx
    ON v3_private.private_import(owner_account_id, imported_at DESC);
COMMENT ON INDEX v3_private.private_import_owner_time_idx IS 'Use: list one account private import history.';

CREATE TABLE v3_private.private_fact (
    private_fact_id uuid PRIMARY KEY,
    private_import_id uuid NOT NULL,
    owner_account_id uuid NOT NULL,
    source_run_id uuid NOT NULL REFERENCES v3_source.source_run(source_run_id),
    fact_kind text NOT NULL,
    fact_key jsonb NOT NULL,
    fact_payload jsonb NOT NULL,
    observed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    withdrawn_at timestamptz,
    FOREIGN KEY (private_import_id, owner_account_id)
        REFERENCES v3_private.private_import(private_import_id, owner_account_id),
    UNIQUE (private_fact_id, owner_account_id),
    CHECK (jsonb_typeof(fact_key) = 'object'),
    CHECK (jsonb_typeof(fact_payload) = 'object')
);

COMMENT ON TABLE v3_private.private_fact IS 'Private evidence only. Deliberately has no canonical-generation or canonical-entity foreign key.';

CREATE INDEX private_fact_import_idx
    ON v3_private.private_fact(private_import_id, created_at);
COMMENT ON INDEX v3_private.private_fact_import_idx IS 'Use: enumerate the private facts produced by one owned import.';

CREATE TABLE v3_private.contribution_receipt (
    contribution_id uuid PRIMARY KEY,
    private_fact_id uuid NOT NULL,
    contributing_account_id uuid NOT NULL,
    audience_code text NOT NULL,
    contribution_purpose text NOT NULL,
    site_publication_allowed boolean NOT NULL DEFAULT false,
    api_redistribution_allowed boolean NOT NULL DEFAULT false,
    bulk_redistribution_allowed boolean NOT NULL DEFAULT false,
    attribution_mode text NOT NULL CHECK (attribution_mode IN (
        'NONE', 'ACCOUNT_PSEUDONYM', 'COMMANDER_NAME', 'CUSTOM_CREDIT'
    )),
    attribution_label text,
    sharing_policy_version text NOT NULL,
    contribution_state text NOT NULL CHECK (contribution_state IN (
        'OFFERED', 'ELIGIBLE', 'REJECTED', 'WITHDRAWN'
    )),
    offered_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    decided_at timestamptz,
    withdrawn_at timestamptz,
    UNIQUE (contribution_id, contributing_account_id),
    FOREIGN KEY (private_fact_id, contributing_account_id)
        REFERENCES v3_private.private_fact(private_fact_id, owner_account_id),
    CHECK (btrim(contribution_purpose) <> ''),
    CHECK ((attribution_mode = 'CUSTOM_CREDIT') = (attribution_label IS NOT NULL)),
    CHECK (attribution_label IS NULL OR btrim(attribution_label) <> ''),
    CHECK ((contribution_state = 'WITHDRAWN') = (withdrawn_at IS NOT NULL))
);

CREATE TABLE v3_private.contribution_withdrawal (
    contribution_withdrawal_id uuid PRIMARY KEY,
    contribution_id uuid NOT NULL,
    requested_by_account_id uuid NOT NULL,
    requested_at timestamptz NOT NULL,
    applied_at timestamptz,
    withdrawal_reason text NOT NULL,
    recomputation_job_id uuid,
    FOREIGN KEY (contribution_id, requested_by_account_id)
        REFERENCES v3_private.contribution_receipt(
            contribution_id, contributing_account_id
        )
);

-- ---------------------------------------------------------------------------
-- Canonical generation control plane (ADR-001, ADR-002, Phase 1D).
-- ---------------------------------------------------------------------------

CREATE TABLE v3_meta.schema_migration (
    migration_name text PRIMARY KEY,
    migration_sha256 bytea NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CHECK (octet_length(migration_sha256) = 32)
);

CREATE TABLE v3_meta.canonical_generation (
    generation_id uuid PRIMARY KEY,
    generation_key text NOT NULL UNIQUE,
    relation_schema text NOT NULL UNIQUE,
    lifecycle_state text NOT NULL DEFAULT 'BUILDING' CHECK (lifecycle_state IN (
        'BUILDING', 'VALIDATING', 'READY', 'PUBLISHED', 'RETIRED', 'FAILED'
    )),
    manifest_sha256 bytea NOT NULL,
    build_source_run_id uuid NOT NULL REFERENCES v3_source.source_run(source_run_id),
    relations_created_at timestamptz,
    validation_started_at timestamptz,
    validation_completed_at timestamptz,
    validation_receipt jsonb,
    published_at timestamptz,
    retired_at timestamptz,
    failed_at timestamptz,
    failure_reason text,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CHECK (generation_key ~ '^[a-z][a-z0-9_]{0,30}$'),
    CHECK (relation_schema = 'v3_gen_' || generation_key),
    CHECK (octet_length(manifest_sha256) = 32),
    CHECK (validation_receipt IS NULL OR jsonb_typeof(validation_receipt) = 'object'),
    CHECK (lifecycle_state NOT IN ('READY', 'PUBLISHED', 'RETIRED') OR validation_completed_at IS NOT NULL),
    CHECK ((lifecycle_state = 'FAILED') = (failed_at IS NOT NULL))
);

COMMENT ON COLUMN v3_meta.canonical_generation.build_source_run_id IS 'Generation-build coordinator run. The complete many-run input set is v3_meta.canonical_generation_input.';

CREATE TABLE v3_meta.canonical_generation_input (
    generation_id uuid NOT NULL REFERENCES v3_meta.canonical_generation(generation_id),
    input_ordinal integer NOT NULL CHECK (input_ordinal >= 0),
    source_id smallint NOT NULL REFERENCES v3_source.source(source_id),
    source_run_id uuid NOT NULL,
    artifact_id uuid,
    input_role text NOT NULL,
    admitted_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    PRIMARY KEY (generation_id, source_run_id),
    UNIQUE (generation_id, input_ordinal),
    UNIQUE (generation_id, source_id, source_run_id),
    FOREIGN KEY (source_run_id, source_id)
        REFERENCES v3_source.source_run(source_run_id, source_id),
    FOREIGN KEY (artifact_id, source_id)
        REFERENCES v3_source.source_artifact(artifact_id, source_id),
    CHECK (btrim(input_role) <> '')
);

CREATE INDEX canonical_generation_input_source_run_idx
    ON v3_meta.canonical_generation_input(source_run_id, generation_id);
COMMENT ON INDEX v3_meta.canonical_generation_input_source_run_idx IS 'Use: trace every canonical generation that admitted a source run.';

CREATE TABLE v3_meta.current_canonical_generation (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    generation_id uuid NOT NULL UNIQUE REFERENCES v3_meta.canonical_generation(generation_id),
    publication_sequence bigint NOT NULL CHECK (publication_sequence > 0),
    published_at timestamptz NOT NULL
);

COMMENT ON TABLE v3_meta.current_canonical_generation IS 'Single-row canonical read pointer. Publication changes this metadata row; it never replaces a view.';

CREATE TABLE v3_meta.canonical_publication_audit (
    publication_sequence bigint PRIMARY KEY,
    from_generation_id uuid REFERENCES v3_meta.canonical_generation(generation_id),
    to_generation_id uuid NOT NULL REFERENCES v3_meta.canonical_generation(generation_id),
    published_at timestamptz NOT NULL,
    published_by text NOT NULL,
    transaction_id bigint NOT NULL,
    reason text NOT NULL
);

-- Sparse group/conflict lineage. It records decisions and hashes, not a
-- universal field-value EAV history.
CREATE TABLE v3_source.canonical_evidence_group (
    canonical_evidence_group_id uuid PRIMARY KEY,
    generation_id uuid NOT NULL REFERENCES v3_meta.canonical_generation(generation_id),
    entity_kind text NOT NULL,
    entity_key jsonb NOT NULL,
    field_group_code text NOT NULL,
    source_id smallint NOT NULL REFERENCES v3_source.source(source_id),
    source_run_id uuid NOT NULL,
    artifact_id uuid,
    contribution_id uuid REFERENCES v3_private.contribution_receipt(contribution_id),
    behavior_class text NOT NULL CHECK (behavior_class IN (
        'IDENTITY_INVARIANT', 'STABLE_PHYSICAL', 'CURRENT_MUTABLE',
        'CURRENT_SET', 'APPEND_ONLY_FACT'
    )),
    reconciliation_policy_version text NOT NULL,
    decision_code text NOT NULL,
    value_sha256 bytea,
    conflict_detail jsonb,
    decided_at timestamptz NOT NULL,
    FOREIGN KEY (source_run_id, source_id)
        REFERENCES v3_source.source_run(source_run_id, source_id),
    FOREIGN KEY (artifact_id, source_id)
        REFERENCES v3_source.source_artifact(artifact_id, source_id),
    CHECK (jsonb_typeof(entity_key) = 'object'),
    CHECK (value_sha256 IS NULL OR octet_length(value_sha256) = 32),
    CHECK (conflict_detail IS NULL OR jsonb_typeof(conflict_detail) = 'object')
);

CREATE INDEX canonical_evidence_generation_entity_idx
    ON v3_source.canonical_evidence_group(generation_id, entity_kind);
COMMENT ON INDEX v3_source.canonical_evidence_generation_entity_idx IS 'Use: audit sparse source/conflict lineage for one published generation and entity kind.';

-- ---------------------------------------------------------------------------
-- Durable workflow and transactional outbox authority (ADR-014, ADR-015).
-- ---------------------------------------------------------------------------

CREATE TABLE v3_async.job (
    job_id uuid PRIMARY KEY,
    job_type text NOT NULL,
    idempotency_key text NOT NULL,
    job_state text NOT NULL DEFAULT 'PENDING' CHECK (job_state IN (
        'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'DEAD_LETTER'
    )),
    payload jsonb NOT NULL,
    priority smallint NOT NULL DEFAULT 0,
    available_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    completed_at timestamptz,
    UNIQUE (job_type, idempotency_key),
    CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX job_runnable_idx
    ON v3_async.job(priority DESC, available_at, created_at)
    WHERE job_state = 'PENDING';
COMMENT ON INDEX v3_async.job_runnable_idx IS 'Use: claim the next durable runnable PostgreSQL job.';

CREATE TABLE v3_async.job_lease (
    job_id uuid PRIMARY KEY REFERENCES v3_async.job(job_id),
    lease_owner text NOT NULL,
    fencing_token bigint NOT NULL CHECK (fencing_token > 0),
    acquired_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    renewed_at timestamptz,
    CHECK (expires_at > acquired_at)
);

CREATE TABLE v3_async.job_attempt (
    job_id uuid NOT NULL REFERENCES v3_async.job(job_id),
    attempt_number integer NOT NULL CHECK (attempt_number > 0),
    fencing_token bigint NOT NULL CHECK (fencing_token > 0),
    attempt_state text NOT NULL CHECK (attempt_state IN (
        'RUNNING', 'SUCCEEDED', 'FAILED', 'ABANDONED'
    )),
    started_at timestamptz NOT NULL,
    finished_at timestamptz,
    error_code text,
    error_detail text,
    PRIMARY KEY (job_id, attempt_number),
    UNIQUE (job_id, fencing_token),
    UNIQUE (job_id, attempt_number, fencing_token),
    CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE v3_async.job_chunk (
    job_id uuid NOT NULL REFERENCES v3_async.job(job_id),
    chunk_key text NOT NULL,
    chunk_ordinal integer NOT NULL CHECK (chunk_ordinal >= 0),
    deterministic_identity_sha256 bytea NOT NULL,
    chunk_state text NOT NULL DEFAULT 'PENDING' CHECK (chunk_state IN (
        'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'QUARANTINED'
    )),
    attempt_number integer,
    fencing_token bigint,
    output_sha256 bytea,
    rows_read bigint NOT NULL DEFAULT 0 CHECK (rows_read >= 0),
    rows_written bigint NOT NULL DEFAULT 0 CHECK (rows_written >= 0),
    rows_rejected bigint NOT NULL DEFAULT 0 CHECK (rows_rejected >= 0),
    started_at timestamptz,
    completed_at timestamptz,
    PRIMARY KEY (job_id, chunk_key),
    UNIQUE (job_id, chunk_ordinal),
    UNIQUE (job_id, deterministic_identity_sha256),
    FOREIGN KEY (job_id, attempt_number, fencing_token)
        REFERENCES v3_async.job_attempt(job_id, attempt_number, fencing_token),
    CHECK (octet_length(deterministic_identity_sha256) = 32),
    CHECK (output_sha256 IS NULL OR octet_length(output_sha256) = 32),
    CHECK ((attempt_number IS NULL) = (fencing_token IS NULL)),
    CHECK (chunk_state = 'PENDING' OR attempt_number IS NOT NULL),
    CHECK (chunk_state <> 'RUNNING' OR started_at IS NOT NULL),
    CHECK ((chunk_state IN ('SUCCEEDED', 'FAILED', 'QUARANTINED')) =
        (completed_at IS NOT NULL)),
    CHECK (chunk_state <> 'SUCCEEDED' OR output_sha256 IS NOT NULL),
    CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE FUNCTION v3_async.enforce_job_chunk_completion_fence()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'UPDATE'
       AND OLD.chunk_state IN ('SUCCEEDED', 'FAILED', 'QUARANTINED') THEN
        IF NEW.chunk_state IS NOT DISTINCT FROM OLD.chunk_state
           AND NEW.attempt_number IS NOT DISTINCT FROM OLD.attempt_number
           AND NEW.fencing_token IS NOT DISTINCT FROM OLD.fencing_token
           AND NEW.output_sha256 IS NOT DISTINCT FROM OLD.output_sha256
           AND NEW.started_at IS NOT DISTINCT FROM OLD.started_at
           AND NEW.completed_at IS NOT DISTINCT FROM OLD.completed_at
           AND NEW.rows_read IS NOT DISTINCT FROM OLD.rows_read
           AND NEW.rows_written IS NOT DISTINCT FROM OLD.rows_written
           AND NEW.rows_rejected IS NOT DISTINCT FROM OLD.rows_rejected THEN
            -- Deliberately permit an exact idempotent/no-op retry only.
            RETURN NEW;
        END IF;

        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = format(
                'terminal completion metadata is immutable for job %s chunk %s',
                NEW.job_id, NEW.chunk_key
            );
    END IF;

    IF NEW.chunk_state IN ('SUCCEEDED', 'FAILED', 'QUARANTINED')
       AND (TG_OP = 'INSERT' OR
            OLD.chunk_state NOT IN ('SUCCEEDED', 'FAILED', 'QUARANTINED')) THEN
        PERFORM 1
          FROM v3_async.job_lease lease
          JOIN v3_async.job job ON job.job_id = lease.job_id
         WHERE lease.job_id = NEW.job_id
           AND lease.fencing_token = NEW.fencing_token
           AND lease.acquired_at <= clock_timestamp()
           AND lease.expires_at > clock_timestamp()
           AND job.job_state = 'RUNNING'
         FOR UPDATE OF lease;
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                MESSAGE = format(
                    'stale, unknown, or expired completion fence for job %s token %s',
                    NEW.job_id, NEW.fencing_token
                );
        END IF;

        PERFORM 1
          FROM v3_async.job_attempt
         WHERE job_id = NEW.job_id
           AND attempt_number = NEW.attempt_number
           AND fencing_token = NEW.fencing_token
           AND attempt_state = 'RUNNING';
        IF NOT FOUND THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                MESSAGE = format(
                    'unknown or inactive completion attempt for job %s attempt %s token %s',
                    NEW.job_id, NEW.attempt_number, NEW.fencing_token
                );
        END IF;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER job_chunk_completion_fence_trigger
BEFORE INSERT OR UPDATE OF
    chunk_state, attempt_number, fencing_token, output_sha256,
    started_at, completed_at, rows_read, rows_written, rows_rejected
ON v3_async.job_chunk
FOR EACH ROW EXECUTE FUNCTION v3_async.enforce_job_chunk_completion_fence();

CREATE TABLE v3_async.outbox_message (
    outbox_message_id uuid PRIMARY KEY,
    producer_scope text NOT NULL,
    idempotency_key text NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id text NOT NULL,
    event_type text NOT NULL,
    contract_version text NOT NULL,
    payload jsonb NOT NULL,
    occurred_at timestamptz NOT NULL,
    available_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    publish_attempts integer NOT NULL DEFAULT 0 CHECK (publish_attempts >= 0),
    published_at timestamptz,
    last_error text,
    UNIQUE (producer_scope, idempotency_key),
    CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX outbox_pending_idx
    ON v3_async.outbox_message(available_at, occurred_at)
    WHERE published_at IS NULL;
COMMENT ON INDEX v3_async.outbox_pending_idx IS 'Use: transactional outbox relay pending-message scan.';

CREATE TABLE v3_async.effect_receipt (
    consumer_name text NOT NULL,
    effect_id text NOT NULL,
    outbox_message_id uuid REFERENCES v3_async.outbox_message(outbox_message_id),
    effect_sha256 bytea,
    completed_at timestamptz NOT NULL,
    result_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (consumer_name, effect_id),
    CHECK (effect_sha256 IS NULL OR octet_length(effect_sha256) = 32),
    CHECK (jsonb_typeof(result_detail) = 'object')
);

COMMENT ON TABLE v3_async.effect_receipt IS 'At-least-once consumer deduplication receipt. It does not claim exactly-once delivery.';

ALTER TABLE v3_private.contribution_withdrawal
    ADD CONSTRAINT contribution_withdrawal_recomputation_job_fk
    FOREIGN KEY (recomputation_job_id) REFERENCES v3_async.job(job_id);

ALTER TABLE v3_identity.personal_data_request
    ADD CONSTRAINT personal_data_request_processing_job_fk
    FOREIGN KEY (processing_job_id) REFERENCES v3_async.job(job_id);

-- ---------------------------------------------------------------------------
-- Validation helpers and per-generation physical relation tooling.
-- ---------------------------------------------------------------------------

CREATE FUNCTION v3_meta.is_percentage_object(value jsonb, is_complete boolean)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $function$
    WITH entries AS MATERIALIZED (
        SELECT entry.value
        FROM jsonb_each(
            CASE
                WHEN jsonb_typeof(value) = 'object' THEN value
                ELSE '{}'::jsonb
            END
        ) AS entry
    ), summary AS (
        SELECT
            count(*) AS entry_count,
            count(*) FILTER (WHERE jsonb_typeof(entries.value) = 'number') AS numeric_count,
            sum((entries.value #>> '{}')::numeric)
                FILTER (WHERE jsonb_typeof(entries.value) = 'number') AS total,
            bool_and(
                CASE
                    WHEN jsonb_typeof(entries.value) = 'number'
                    THEN (entries.value #>> '{}')::numeric BETWEEN 0 AND 100
                    ELSE false
                END
            ) AS values_in_range
        FROM entries
    )
    SELECT
        jsonb_typeof(value) = 'object'
        AND entry_count > 0
        AND numeric_count = entry_count
        AND values_in_range
        AND (NOT is_complete OR abs(total - 100) <= 0.0001)
    FROM summary;
$function$;

COMMENT ON FUNCTION v3_meta.is_percentage_object(jsonb, boolean) IS 'Validates non-empty percentage maps with individual values in [0,100]; complete maps sum to 100 while incomplete source maps retain their raw total without treating omitted keys as zero.';

CREATE FUNCTION v3_meta.create_canonical_generation_relations(target_generation_id uuid)
RETURNS text
LANGUAGE plpgsql
AS $function$
DECLARE
    target_schema text;
    target_state text;
BEGIN
    SELECT relation_schema, lifecycle_state
      INTO target_schema, target_state
      FROM v3_meta.canonical_generation
     WHERE generation_id = target_generation_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'unknown canonical generation %', target_generation_id;
    END IF;
    IF target_state <> 'BUILDING' THEN
        RAISE EXCEPTION 'generation % is %, expected BUILDING', target_generation_id, target_state;
    END IF;
    IF target_schema !~ '^v3_gen_[a-z][a-z0-9_]{0,30}$' THEN
        RAISE EXCEPTION 'unsafe generation schema %', target_schema;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = target_schema) THEN
        RAISE EXCEPTION 'generation schema % already exists', target_schema;
    END IF;

    EXECUTE format('CREATE SCHEMA %I', target_schema);
    EXECUTE format('COMMENT ON SCHEMA %I IS %L', target_schema,
        'V3 canonical generation physical relations; immutable after publication.');

    EXECUTE format($ddl$
        CREATE TABLE %I.systems (
            id64 bigint NOT NULL,
            name text NOT NULL,
            x_ly double precision NOT NULL,
            y_ly double precision NOT NULL,
            z_ly double precision NOT NULL,
            source_body_count integer,
            loaded_body_count integer NOT NULL,
            galaxy_region_id smallint,
            grid_x integer NOT NULL,
            grid_y integer NOT NULL,
            grid_z integer NOT NULL,
            macro_grid_key bigint NOT NULL,
            source_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            source_updated_at timestamptz,
            freshness_checked_at timestamptz NOT NULL,
            lifecycle_state text NOT NULL DEFAULT 'ACTIVE',
            last_present_run_id uuid,
            last_present_at timestamptz,
            first_missing_run_id uuid,
            first_missing_at timestamptz,
            last_missing_run_id uuid,
            retired_at timestamptz,
            retired_reason text,
            CHECK (source_body_count IS NULL OR source_body_count >= 0),
            CHECK (loaded_body_count >= 0),
            CHECK (lifecycle_state IN ('ACTIVE', 'MISSING_CANDIDATE', 'RETIRED')),
            CHECK (lifecycle_state <> 'RETIRED' OR retired_at IS NOT NULL),
            CHECK ((first_missing_run_id IS NULL) = (first_missing_at IS NULL))
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.bodies (
            body_pk bigint NOT NULL,
            system_id64 bigint NOT NULL,
            source_body_id64 bigint,
            frontier_body_id bigint,
            direct_parent_body_pk bigint,
            name text NOT NULL,
            body_type_id smallint,
            atmosphere_classification_id smallint,
            terraforming_state_id smallint,
            volcanism_type_id smallint,
            is_landable boolean,
            is_tidally_locked boolean,
            is_main_star boolean,
            spectral_class text,
            luminosity_class text,
            absolute_magnitude double precision,
            radius_km double precision,
            planet_mass_earth double precision,
            stellar_mass_solar double precision,
            surface_gravity_g double precision,
            surface_pressure_atm double precision,
            surface_temperature_k double precision,
            semi_major_axis_km double precision,
            orbital_period_days double precision,
            rotation_period_days double precision,
            eccentricity double precision,
            orbital_inclination_deg double precision,
            ascending_node_deg double precision,
            argument_of_periapsis_deg double precision,
            mean_anomaly_deg double precision,
            axial_tilt_rad double precision,
            distance_from_arrival_ls double precision,
            stellar_age_myr double precision,
            signals_complete boolean,
            genera_complete boolean,
            source_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            source_updated_at timestamptz,
            freshness_checked_at timestamptz NOT NULL,
            lifecycle_state text NOT NULL DEFAULT 'ACTIVE',
            last_present_run_id uuid,
            last_present_at timestamptz,
            first_missing_run_id uuid,
            first_missing_at timestamptz,
            last_missing_run_id uuid,
            retired_at timestamptz,
            retired_reason text,
            CHECK (eccentricity IS NULL OR eccentricity BETWEEN 0 AND 1),
            CHECK (mean_anomaly_deg IS NULL OR
                (mean_anomaly_deg >= 0 AND mean_anomaly_deg <= 360)),
            CHECK (absolute_magnitude IS NULL OR absolute_magnitude NOT IN (
                'NaN'::double precision,
                'Infinity'::double precision,
                '-Infinity'::double precision
            )),
            CHECK (spectral_class IS NULL OR btrim(spectral_class) <> ''),
            CHECK (luminosity_class IS NULL OR btrim(luminosity_class) <> ''),
            CHECK (lifecycle_state IN ('ACTIVE', 'MISSING_CANDIDATE', 'RETIRED')),
            CHECK (lifecycle_state <> 'RETIRED' OR retired_at IS NOT NULL),
            CHECK ((first_missing_run_id IS NULL) = (first_missing_at IS NULL))
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.body_composition (
            body_pk bigint NOT NULL,
            ice_pct real,
            metal_pct real,
            rock_pct real,
            materials jsonb,
            materials_complete boolean,
            atmosphere jsonb,
            atmosphere_complete boolean,
            source_run_id uuid NOT NULL,
            observed_at timestamptz,
            CHECK (ice_pct IS NULL OR ice_pct BETWEEN 0 AND 100),
            CHECK (metal_pct IS NULL OR metal_pct BETWEEN 0 AND 100),
            CHECK (rock_pct IS NULL OR rock_pct BETWEEN 0 AND 100),
            CHECK ((materials IS NULL AND materials_complete IS NULL) OR
                (materials IS NOT NULL AND materials_complete IS NOT NULL AND
                 v3_meta.is_percentage_object(materials, materials_complete))),
            CHECK ((atmosphere IS NULL AND atmosphere_complete IS NULL) OR
                (atmosphere IS NOT NULL AND atmosphere_complete IS NOT NULL AND
                 v3_meta.is_percentage_object(atmosphere, atmosphere_complete))),
            CHECK (
                ice_pct IS NOT NULL OR metal_pct IS NOT NULL OR rock_pct IS NOT NULL
                OR materials IS NOT NULL OR atmosphere IS NOT NULL
            )
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.body_alias (
            body_pk bigint NOT NULL,
            identity_namespace_id smallint NOT NULL,
            external_id text NOT NULL,
            source_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.body_parent_evidence (
            body_pk bigint NOT NULL,
            system_id64 bigint NOT NULL,
            source_run_id uuid NOT NULL,
            source_parent_ordinal smallint NOT NULL DEFAULT 0,
            raw_parent_label text NOT NULL,
            raw_parent_id bigint,
            resolution_state text NOT NULL,
            resolved_parent_body_pk bigint,
            detail jsonb NOT NULL DEFAULT '{}'::jsonb,
            CHECK (source_parent_ordinal = 0),
            CHECK (resolution_state IN ('UNRESOLVED', 'RESOLVED', 'CONFLICT', 'INVALID')),
            CHECK ((resolution_state = 'RESOLVED') = (resolved_parent_body_pk IS NOT NULL)),
            CHECK (jsonb_typeof(detail) = 'object')
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.rings (
            ring_pk bigint NOT NULL,
            body_pk bigint NOT NULL,
            system_id64 bigint NOT NULL,
            source_ring_id64 bigint,
            kind text NOT NULL,
            name text NOT NULL,
            ring_type_id smallint,
            reserve_type_id smallint,
            inner_radius_km double precision,
            outer_radius_km double precision,
            mass_mt double precision,
            signals_complete boolean,
            source_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            source_updated_at timestamptz,
            freshness_checked_at timestamptz NOT NULL,
            lifecycle_state text NOT NULL DEFAULT 'ACTIVE',
            last_present_run_id uuid,
            last_present_at timestamptz,
            first_missing_run_id uuid,
            first_missing_at timestamptz,
            last_missing_run_id uuid,
            retired_at timestamptz,
            retired_reason text,
            CHECK (kind IN ('RING', 'BELT')),
            CHECK (inner_radius_km IS NULL OR inner_radius_km >= 0),
            CHECK (outer_radius_km IS NULL OR outer_radius_km >= 0),
            CHECK (inner_radius_km IS NULL OR outer_radius_km IS NULL OR outer_radius_km >= inner_radius_km),
            CHECK (mass_mt IS NULL OR mass_mt >= 0),
            CHECK (lifecycle_state IN ('ACTIVE', 'MISSING_CANDIDATE', 'RETIRED')),
            CHECK (lifecycle_state <> 'RETIRED' OR retired_at IS NOT NULL),
            CHECK ((first_missing_run_id IS NULL) = (first_missing_at IS NULL))
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.body_signal_current (
            body_pk bigint NOT NULL,
            signal_type_id smallint NOT NULL,
            signal_count integer NOT NULL CHECK (signal_count >= 0),
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.body_genus_current (
            body_pk bigint NOT NULL,
            genus_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.ring_signal_current (
            ring_pk bigint NOT NULL,
            signal_type_id smallint NOT NULL,
            signal_count integer NOT NULL CHECK (signal_count >= 0),
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.stations (
            station_pk bigint NOT NULL,
            market_id bigint,
            system_id64 bigint NOT NULL,
            name text NOT NULL,
            station_type_id smallint,
            distance_from_arrival_ls double precision,
            services_complete boolean,
            economies_complete boolean,
            is_fleet_carrier boolean NOT NULL DEFAULT false,
            source_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            source_updated_at timestamptz,
            freshness_checked_at timestamptz NOT NULL,
            lifecycle_state text NOT NULL DEFAULT 'ACTIVE',
            last_present_run_id uuid,
            last_present_at timestamptz,
            first_missing_run_id uuid,
            first_missing_at timestamptz,
            last_missing_run_id uuid,
            retired_at timestamptz,
            retired_reason text,
            CHECK (distance_from_arrival_ls IS NULL OR distance_from_arrival_ls >= 0),
            CHECK (lifecycle_state IN ('ACTIVE', 'MISSING_CANDIDATE', 'RETIRED')),
            CHECK (lifecycle_state <> 'RETIRED' OR retired_at IS NOT NULL),
            CHECK ((first_missing_run_id IS NULL) = (first_missing_at IS NULL))
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.station_alias (
            station_pk bigint NOT NULL,
            identity_namespace_id smallint NOT NULL,
            external_id text NOT NULL,
            source_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.station_placement (
            station_pk bigint NOT NULL,
            system_id64 bigint NOT NULL,
            body_pk bigint,
            latitude_deg double precision,
            longitude_deg double precision,
            association_state text NOT NULL,
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL,
            evidence_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
            CHECK (latitude_deg IS NULL OR latitude_deg BETWEEN -90 AND 90),
            CHECK (longitude_deg IS NULL OR longitude_deg BETWEEN -180 AND 180),
            CHECK (association_state IN ('UNKNOWN', 'SYSTEM_ONLY', 'BODY_RESOLVED', 'CONFLICT', 'REJECTED')),
            CHECK (association_state <> 'BODY_RESOLVED' OR body_pk IS NOT NULL),
            CHECK (jsonb_typeof(evidence_detail) = 'object')
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.station_service_current (
            station_pk bigint NOT NULL,
            station_service_id smallint NOT NULL,
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL
        )
    $ddl$, target_schema);

    EXECUTE format($ddl$
        CREATE TABLE %I.station_economy_current (
            station_pk bigint NOT NULL,
            economy_id smallint NOT NULL,
            economy_weight double precision,
            is_primary boolean NOT NULL DEFAULT false,
            is_secondary boolean NOT NULL DEFAULT false,
            source_run_id uuid NOT NULL,
            observed_at timestamptz NOT NULL,
            CHECK (economy_weight >= 0),
            CHECK (economy_weight NOT IN ('NaN'::double precision, 'Infinity'::double precision, '-Infinity'::double precision))
        )
    $ddl$, target_schema);

    UPDATE v3_meta.canonical_generation
       SET relations_created_at = transaction_timestamp()
     WHERE generation_id = target_generation_id;

    RETURN target_schema;
END;
$function$;

COMMENT ON FUNCTION v3_meta.create_canonical_generation_relations(uuid) IS 'Creates fresh logged heaps only. Secondary indexes and FKs are deliberately deferred until post-COPY finalization.';

CREATE FUNCTION v3_meta.finalize_canonical_generation(
    target_generation_id uuid,
    receipt jsonb
)
RETURNS text
LANGUAGE plpgsql
AS $function$
DECLARE
    target_schema text;
    target_state text;
    ddl text;
    missing_manifest_input boolean;
BEGIN
    SELECT relation_schema, lifecycle_state
      INTO target_schema, target_state
      FROM v3_meta.canonical_generation
     WHERE generation_id = target_generation_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'unknown canonical generation %', target_generation_id;
    END IF;
    IF target_state <> 'BUILDING' THEN
        RAISE EXCEPTION 'generation % is %, expected BUILDING', target_generation_id, target_state;
    END IF;
    IF receipt IS NULL OR jsonb_typeof(receipt) <> 'object' THEN
        RAISE EXCEPTION 'validation receipt must be a JSON object';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = target_schema) THEN
        RAISE EXCEPTION 'generation schema % is missing', target_schema;
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM v3_meta.canonical_generation_input
         WHERE generation_id = target_generation_id
    ) THEN
        RAISE EXCEPTION 'generation % has no input manifest', target_generation_id;
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM v3_meta.canonical_generation generation
          JOIN v3_meta.canonical_generation_input input
            ON input.generation_id = generation.generation_id
           AND input.source_run_id = generation.build_source_run_id
         WHERE generation.generation_id = target_generation_id
    ) THEN
        RAISE EXCEPTION 'generation % build coordinator run is absent from its input manifest',
            target_generation_id;
    END IF;

    EXECUTE format($query$
        SELECT EXISTS (
            SELECT 1
              FROM (
                    SELECT source_run_id FROM %1$I.systems
                    UNION SELECT last_present_run_id FROM %1$I.systems
                    UNION SELECT first_missing_run_id FROM %1$I.systems
                    UNION SELECT last_missing_run_id FROM %1$I.systems
                    UNION SELECT source_run_id FROM %1$I.bodies
                    UNION SELECT last_present_run_id FROM %1$I.bodies
                    UNION SELECT first_missing_run_id FROM %1$I.bodies
                    UNION SELECT last_missing_run_id FROM %1$I.bodies
                    UNION SELECT source_run_id FROM %1$I.body_composition
                    UNION SELECT source_run_id FROM %1$I.body_alias
                    UNION SELECT source_run_id FROM %1$I.body_parent_evidence
                    UNION SELECT source_run_id FROM %1$I.rings
                    UNION SELECT last_present_run_id FROM %1$I.rings
                    UNION SELECT first_missing_run_id FROM %1$I.rings
                    UNION SELECT last_missing_run_id FROM %1$I.rings
                    UNION SELECT source_run_id FROM %1$I.body_signal_current
                    UNION SELECT source_run_id FROM %1$I.body_genus_current
                    UNION SELECT source_run_id FROM %1$I.ring_signal_current
                    UNION SELECT source_run_id FROM %1$I.stations
                    UNION SELECT last_present_run_id FROM %1$I.stations
                    UNION SELECT first_missing_run_id FROM %1$I.stations
                    UNION SELECT last_missing_run_id FROM %1$I.stations
                    UNION SELECT source_run_id FROM %1$I.station_alias
                    UNION SELECT source_run_id FROM %1$I.station_placement
                    UNION SELECT source_run_id FROM %1$I.station_service_current
                    UNION SELECT source_run_id FROM %1$I.station_economy_current
              ) used
              LEFT JOIN v3_meta.canonical_generation_input input
                ON input.generation_id = $1
               AND input.source_run_id = used.source_run_id
             WHERE used.source_run_id IS NOT NULL
               AND input.source_run_id IS NULL
        )
    $query$, target_schema)
    INTO missing_manifest_input
    USING target_generation_id;

    IF missing_manifest_input THEN
        RAISE EXCEPTION 'generation % contains source runs absent from its input manifest',
            target_generation_id;
    END IF;

    UPDATE v3_meta.canonical_generation
       SET lifecycle_state = 'VALIDATING',
           validation_started_at = transaction_timestamp()
     WHERE generation_id = target_generation_id;

    -- Identity, FK-helper, and named serving indexes. No GIN/trigram indexes.
    FOREACH ddl IN ARRAY ARRAY[
        format('CREATE UNIQUE INDEX systems_pk ON %I.systems(id64)', target_schema),
        format('CREATE INDEX systems_macro_grid_idx ON %I.systems(macro_grid_key,id64)', target_schema),
        format('CREATE UNIQUE INDEX bodies_pk ON %I.bodies(body_pk)', target_schema),
        format('CREATE UNIQUE INDEX bodies_system_body_uidx ON %I.bodies(system_id64,body_pk)', target_schema),
        format('CREATE UNIQUE INDEX bodies_source_id64_uidx ON %I.bodies(source_body_id64) WHERE source_body_id64 IS NOT NULL', target_schema),
        format('CREATE UNIQUE INDEX bodies_frontier_body_uidx ON %I.bodies(system_id64,frontier_body_id) WHERE frontier_body_id IS NOT NULL', target_schema),
        format('CREATE INDEX bodies_system_idx ON %I.bodies(system_id64,body_pk)', target_schema),
        format('CREATE INDEX bodies_parent_idx ON %I.bodies(system_id64,direct_parent_body_pk) WHERE direct_parent_body_pk IS NOT NULL', target_schema),
        format('CREATE UNIQUE INDEX body_composition_pk ON %I.body_composition(body_pk)', target_schema),
        format('CREATE UNIQUE INDEX body_alias_identity_uidx ON %I.body_alias(identity_namespace_id,external_id)', target_schema),
        format('CREATE INDEX body_alias_body_idx ON %I.body_alias(body_pk)', target_schema),
        format('CREATE UNIQUE INDEX body_parent_evidence_pk ON %I.body_parent_evidence(body_pk,source_run_id,source_parent_ordinal)', target_schema),
        format('CREATE UNIQUE INDEX rings_pk ON %I.rings(ring_pk)', target_schema),
        format('CREATE UNIQUE INDEX rings_system_ring_uidx ON %I.rings(system_id64,ring_pk)', target_schema),
        format('CREATE UNIQUE INDEX rings_source_identity_uidx ON %I.rings(source_id,source_ring_id64) WHERE source_ring_id64 IS NOT NULL', target_schema),
        format('CREATE INDEX rings_body_idx ON %I.rings(system_id64,body_pk,ring_pk)', target_schema),
        format('CREATE UNIQUE INDEX body_signal_current_pk ON %I.body_signal_current(body_pk,signal_type_id)', target_schema),
        format('CREATE UNIQUE INDEX body_genus_current_pk ON %I.body_genus_current(body_pk,genus_id)', target_schema),
        format('CREATE UNIQUE INDEX ring_signal_current_pk ON %I.ring_signal_current(ring_pk,signal_type_id)', target_schema),
        format('CREATE UNIQUE INDEX stations_pk ON %I.stations(station_pk)', target_schema),
        format('CREATE UNIQUE INDEX stations_system_station_uidx ON %I.stations(system_id64,station_pk)', target_schema),
        format('CREATE UNIQUE INDEX stations_market_id_uidx ON %I.stations(market_id) WHERE market_id IS NOT NULL', target_schema),
        format('CREATE INDEX stations_system_idx ON %I.stations(system_id64,station_pk)', target_schema),
        format('CREATE UNIQUE INDEX station_alias_identity_uidx ON %I.station_alias(identity_namespace_id,external_id)', target_schema),
        format('CREATE INDEX station_alias_station_idx ON %I.station_alias(station_pk)', target_schema),
        format('CREATE UNIQUE INDEX station_placement_pk ON %I.station_placement(station_pk)', target_schema),
        format('CREATE INDEX station_placement_body_idx ON %I.station_placement(system_id64,body_pk,station_pk) WHERE body_pk IS NOT NULL', target_schema),
        format('CREATE UNIQUE INDEX station_service_current_pk ON %I.station_service_current(station_pk,station_service_id)', target_schema),
        format('CREATE UNIQUE INDEX station_economy_current_pk ON %I.station_economy_current(station_pk,economy_id)', target_schema)
    ] LOOP
        EXECUTE ddl;
    END LOOP;

    -- Query/use documentation for every non-integrity generation index.
    FOREACH ddl IN ARRAY ARRAY[
        format('COMMENT ON INDEX %I.systems_macro_grid_idx IS %L', target_schema,
            'Use: bounded macro-grid system candidate scan.'),
        format('COMMENT ON INDEX %I.bodies_system_idx IS %L', target_schema,
            'Use: list bodies for one system in stable body key order.'),
        format('COMMENT ON INDEX %I.bodies_parent_idx IS %L', target_schema,
            'Use: list direct children for one same-system parent.'),
        format('COMMENT ON INDEX %I.body_alias_body_idx IS %L', target_schema,
            'Use: list sparse additional identities for one body.'),
        format('COMMENT ON INDEX %I.rings_body_idx IS %L', target_schema,
            'Use: list rings and belts for one body.'),
        format('COMMENT ON INDEX %I.stations_system_idx IS %L', target_schema,
            'Use: list stations for one system in stable station key order.'),
        format('COMMENT ON INDEX %I.station_alias_station_idx IS %L', target_schema,
            'Use: list sparse additional identities for one station.'),
        format('COMMENT ON INDEX %I.station_placement_body_idx IS %L', target_schema,
            'Use: list stations resolved to one body within a system.')
    ] LOOP
        EXECUTE ddl;
    END LOOP;

    FOREACH ddl IN ARRAY ARRAY[
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_pk PRIMARY KEY USING INDEX systems_pk', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_pk PRIMARY KEY USING INDEX bodies_pk', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_system_body_unique UNIQUE USING INDEX bodies_system_body_uidx', target_schema),
        format('ALTER TABLE %I.body_composition ADD CONSTRAINT body_composition_pk PRIMARY KEY USING INDEX body_composition_pk', target_schema),
        format('ALTER TABLE %I.body_alias ADD CONSTRAINT body_alias_pk PRIMARY KEY USING INDEX body_alias_identity_uidx', target_schema),
        format('ALTER TABLE %I.body_parent_evidence ADD CONSTRAINT body_parent_evidence_pk PRIMARY KEY USING INDEX body_parent_evidence_pk', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_pk PRIMARY KEY USING INDEX rings_pk', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_system_ring_unique UNIQUE USING INDEX rings_system_ring_uidx', target_schema),
        format('ALTER TABLE %I.body_signal_current ADD CONSTRAINT body_signal_current_pk PRIMARY KEY USING INDEX body_signal_current_pk', target_schema),
        format('ALTER TABLE %I.body_genus_current ADD CONSTRAINT body_genus_current_pk PRIMARY KEY USING INDEX body_genus_current_pk', target_schema),
        format('ALTER TABLE %I.ring_signal_current ADD CONSTRAINT ring_signal_current_pk PRIMARY KEY USING INDEX ring_signal_current_pk', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_pk PRIMARY KEY USING INDEX stations_pk', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_system_station_unique UNIQUE USING INDEX stations_system_station_uidx', target_schema),
        format('ALTER TABLE %I.station_alias ADD CONSTRAINT station_alias_pk PRIMARY KEY USING INDEX station_alias_identity_uidx', target_schema),
        format('ALTER TABLE %I.station_placement ADD CONSTRAINT station_placement_pk PRIMARY KEY USING INDEX station_placement_pk', target_schema),
        format('ALTER TABLE %I.station_service_current ADD CONSTRAINT station_service_current_pk PRIMARY KEY USING INDEX station_service_current_pk', target_schema),
        format('ALTER TABLE %I.station_economy_current ADD CONSTRAINT station_economy_current_pk PRIMARY KEY USING INDEX station_economy_current_pk', target_schema)
    ] LOOP
        EXECUTE ddl;
    END LOOP;

    -- Large FKs follow the accepted NOT VALID -> VALIDATE sequence.
    FOREACH ddl IN ARRAY ARRAY[
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_region_fk FOREIGN KEY(galaxy_region_id) REFERENCES v3_vocab.galaxy_region(galaxy_region_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_source_fk FOREIGN KEY(source_id) REFERENCES v3_source.source(source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_source_run_source_fk FOREIGN KEY(source_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_last_present_run_source_fk FOREIGN KEY(last_present_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_first_missing_run_source_fk FOREIGN KEY(first_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.systems ADD CONSTRAINT systems_last_missing_run_source_fk FOREIGN KEY(last_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_system_fk FOREIGN KEY(system_id64) REFERENCES %I.systems(id64) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_parent_fk FOREIGN KEY(system_id64,direct_parent_body_pk) REFERENCES %I.bodies(system_id64,body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_type_fk FOREIGN KEY(body_type_id) REFERENCES v3_vocab.body_type(body_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_atmosphere_classification_fk FOREIGN KEY(atmosphere_classification_id) REFERENCES v3_vocab.atmosphere_classification(atmosphere_classification_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_terraforming_state_fk FOREIGN KEY(terraforming_state_id) REFERENCES v3_vocab.terraforming_state(terraforming_state_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_volcanism_type_fk FOREIGN KEY(volcanism_type_id) REFERENCES v3_vocab.volcanism_type(volcanism_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_source_fk FOREIGN KEY(source_id) REFERENCES v3_source.source(source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_source_run_source_fk FOREIGN KEY(source_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_last_present_run_source_fk FOREIGN KEY(last_present_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_first_missing_run_source_fk FOREIGN KEY(first_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.bodies ADD CONSTRAINT bodies_last_missing_run_source_fk FOREIGN KEY(last_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_composition ADD CONSTRAINT body_composition_body_fk FOREIGN KEY(body_pk) REFERENCES %I.bodies(body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.body_composition ADD CONSTRAINT body_composition_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_alias ADD CONSTRAINT body_alias_body_fk FOREIGN KEY(body_pk) REFERENCES %I.bodies(body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.body_alias ADD CONSTRAINT body_alias_namespace_fk FOREIGN KEY(identity_namespace_id) REFERENCES v3_vocab.identity_namespace(identity_namespace_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_alias ADD CONSTRAINT body_alias_source_fk FOREIGN KEY(source_id) REFERENCES v3_source.source(source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_alias ADD CONSTRAINT body_alias_source_run_source_fk FOREIGN KEY(source_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_parent_evidence ADD CONSTRAINT body_parent_evidence_body_fk FOREIGN KEY(system_id64,body_pk) REFERENCES %I.bodies(system_id64,body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.body_parent_evidence ADD CONSTRAINT body_parent_evidence_resolved_fk FOREIGN KEY(system_id64,resolved_parent_body_pk) REFERENCES %I.bodies(system_id64,body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.body_parent_evidence ADD CONSTRAINT body_parent_evidence_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_body_fk FOREIGN KEY(system_id64,body_pk) REFERENCES %I.bodies(system_id64,body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_type_fk FOREIGN KEY(ring_type_id) REFERENCES v3_vocab.ring_type(ring_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_reserve_fk FOREIGN KEY(reserve_type_id) REFERENCES v3_vocab.reserve_type(reserve_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_source_fk FOREIGN KEY(source_id) REFERENCES v3_source.source(source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_source_run_source_fk FOREIGN KEY(source_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_last_present_run_source_fk FOREIGN KEY(last_present_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_first_missing_run_source_fk FOREIGN KEY(first_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.rings ADD CONSTRAINT rings_last_missing_run_source_fk FOREIGN KEY(last_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_signal_current ADD CONSTRAINT body_signal_body_fk FOREIGN KEY(body_pk) REFERENCES %I.bodies(body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.body_signal_current ADD CONSTRAINT body_signal_type_fk FOREIGN KEY(signal_type_id) REFERENCES v3_vocab.signal_type(signal_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_signal_current ADD CONSTRAINT body_signal_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_genus_current ADD CONSTRAINT body_genus_body_fk FOREIGN KEY(body_pk) REFERENCES %I.bodies(body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.body_genus_current ADD CONSTRAINT body_genus_token_fk FOREIGN KEY(genus_id) REFERENCES v3_vocab.genus(genus_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.body_genus_current ADD CONSTRAINT body_genus_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.ring_signal_current ADD CONSTRAINT ring_signal_ring_fk FOREIGN KEY(ring_pk) REFERENCES %I.rings(ring_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.ring_signal_current ADD CONSTRAINT ring_signal_type_fk FOREIGN KEY(signal_type_id) REFERENCES v3_vocab.signal_type(signal_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.ring_signal_current ADD CONSTRAINT ring_signal_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_system_fk FOREIGN KEY(system_id64) REFERENCES %I.systems(id64) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_type_fk FOREIGN KEY(station_type_id) REFERENCES v3_vocab.station_type(station_type_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_source_fk FOREIGN KEY(source_id) REFERENCES v3_source.source(source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_source_run_source_fk FOREIGN KEY(source_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_last_present_run_source_fk FOREIGN KEY(last_present_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_first_missing_run_source_fk FOREIGN KEY(first_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.stations ADD CONSTRAINT stations_last_missing_run_source_fk FOREIGN KEY(last_missing_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_alias ADD CONSTRAINT station_alias_station_fk FOREIGN KEY(station_pk) REFERENCES %I.stations(station_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.station_alias ADD CONSTRAINT station_alias_namespace_fk FOREIGN KEY(identity_namespace_id) REFERENCES v3_vocab.identity_namespace(identity_namespace_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_alias ADD CONSTRAINT station_alias_source_fk FOREIGN KEY(source_id) REFERENCES v3_source.source(source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_alias ADD CONSTRAINT station_alias_source_run_source_fk FOREIGN KEY(source_run_id,source_id) REFERENCES v3_source.source_run(source_run_id,source_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_placement ADD CONSTRAINT station_placement_station_fk FOREIGN KEY(system_id64,station_pk) REFERENCES %I.stations(system_id64,station_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.station_placement ADD CONSTRAINT station_placement_body_fk FOREIGN KEY(system_id64,body_pk) REFERENCES %I.bodies(system_id64,body_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.station_placement ADD CONSTRAINT station_placement_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_service_current ADD CONSTRAINT station_service_station_fk FOREIGN KEY(station_pk) REFERENCES %I.stations(station_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.station_service_current ADD CONSTRAINT station_service_token_fk FOREIGN KEY(station_service_id) REFERENCES v3_vocab.station_service(station_service_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_service_current ADD CONSTRAINT station_service_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_economy_current ADD CONSTRAINT station_economy_station_fk FOREIGN KEY(station_pk) REFERENCES %I.stations(station_pk) NOT VALID', target_schema, target_schema),
        format('ALTER TABLE %I.station_economy_current ADD CONSTRAINT station_economy_token_fk FOREIGN KEY(economy_id) REFERENCES v3_vocab.economy(economy_id) NOT VALID', target_schema),
        format('ALTER TABLE %I.station_economy_current ADD CONSTRAINT station_economy_source_run_fk FOREIGN KEY(source_run_id) REFERENCES v3_source.source_run(source_run_id) NOT VALID', target_schema)
    ] LOOP
        EXECUTE ddl;
    END LOOP;

    FOR ddl IN
        SELECT format(
            'ALTER TABLE %I.%I VALIDATE CONSTRAINT %I',
            target_schema,
            table_name,
            constraint_name
        )
        FROM (VALUES
            ('systems','systems_region_fk'), ('systems','systems_source_fk'),
            ('systems','systems_source_run_source_fk'),
            ('systems','systems_last_present_run_source_fk'),
            ('systems','systems_first_missing_run_source_fk'),
            ('systems','systems_last_missing_run_source_fk'),
            ('bodies','bodies_system_fk'), ('bodies','bodies_parent_fk'), ('bodies','bodies_type_fk'),
            ('bodies','bodies_atmosphere_classification_fk'),
            ('bodies','bodies_terraforming_state_fk'), ('bodies','bodies_volcanism_type_fk'),
            ('bodies','bodies_source_fk'), ('bodies','bodies_source_run_source_fk'),
            ('bodies','bodies_last_present_run_source_fk'),
            ('bodies','bodies_first_missing_run_source_fk'),
            ('bodies','bodies_last_missing_run_source_fk'),
            ('body_composition','body_composition_body_fk'), ('body_composition','body_composition_source_run_fk'),
            ('body_alias','body_alias_body_fk'), ('body_alias','body_alias_namespace_fk'),
            ('body_alias','body_alias_source_fk'), ('body_alias','body_alias_source_run_source_fk'),
            ('body_parent_evidence','body_parent_evidence_body_fk'),
            ('body_parent_evidence','body_parent_evidence_resolved_fk'),
            ('body_parent_evidence','body_parent_evidence_source_run_fk'),
            ('rings','rings_body_fk'), ('rings','rings_type_fk'), ('rings','rings_reserve_fk'),
            ('rings','rings_source_fk'), ('rings','rings_source_run_source_fk'),
            ('rings','rings_last_present_run_source_fk'),
            ('rings','rings_first_missing_run_source_fk'),
            ('rings','rings_last_missing_run_source_fk'),
            ('body_signal_current','body_signal_body_fk'), ('body_signal_current','body_signal_type_fk'),
            ('body_signal_current','body_signal_source_run_fk'),
            ('body_genus_current','body_genus_body_fk'), ('body_genus_current','body_genus_token_fk'),
            ('body_genus_current','body_genus_source_run_fk'),
            ('ring_signal_current','ring_signal_ring_fk'), ('ring_signal_current','ring_signal_type_fk'),
            ('ring_signal_current','ring_signal_source_run_fk'),
            ('stations','stations_system_fk'), ('stations','stations_type_fk'),
            ('stations','stations_source_fk'), ('stations','stations_source_run_source_fk'),
            ('stations','stations_last_present_run_source_fk'),
            ('stations','stations_first_missing_run_source_fk'),
            ('stations','stations_last_missing_run_source_fk'),
            ('station_alias','station_alias_station_fk'), ('station_alias','station_alias_namespace_fk'),
            ('station_alias','station_alias_source_fk'), ('station_alias','station_alias_source_run_source_fk'),
            ('station_placement','station_placement_station_fk'), ('station_placement','station_placement_body_fk'),
            ('station_placement','station_placement_source_run_fk'),
            ('station_service_current','station_service_station_fk'),
            ('station_service_current','station_service_token_fk'),
            ('station_service_current','station_service_source_run_fk'),
            ('station_economy_current','station_economy_station_fk'),
            ('station_economy_current','station_economy_token_fk'),
            ('station_economy_current','station_economy_source_run_fk')
        ) AS constraints(table_name, constraint_name)
    LOOP
        EXECUTE ddl;
    END LOOP;

    UPDATE v3_meta.canonical_generation
       SET lifecycle_state = 'READY',
           validation_completed_at = transaction_timestamp(),
           validation_receipt = receipt
     WHERE generation_id = target_generation_id;

    RETURN target_schema;
EXCEPTION WHEN OTHERS THEN
    -- Transactional DDL rolls back all partial indexes/FKs. The caller records
    -- FAILED in a separate transaction after observing the exception.
    RAISE;
END;
$function$;

COMMENT ON FUNCTION v3_meta.finalize_canonical_generation(uuid, jsonb) IS 'Post-COPY build: identity/serving indexes, FKs as NOT VALID, validation, then READY.';

CREATE FUNCTION v3_meta.publish_canonical_generation(
    target_generation_id uuid,
    publication_reason text,
    publication_actor text
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
    prior_generation_id uuid;
    next_sequence bigint;
    target_state text;
    target_validated_at timestamptz;
    target_schema text;
    physical_relation_count integer;
BEGIN
    IF publication_reason IS NULL OR btrim(publication_reason) = '' THEN
        RAISE EXCEPTION 'publication reason is required';
    END IF;
    IF publication_actor IS NULL OR btrim(publication_actor) = '' THEN
        RAISE EXCEPTION 'publication actor is required';
    END IF;

    PERFORM pg_advisory_xact_lock(hashtextextended('edfinder-v3-canonical-publication', 0));

    SELECT lifecycle_state, validation_completed_at, relation_schema
      INTO target_state, target_validated_at, target_schema
      FROM v3_meta.canonical_generation
     WHERE generation_id = target_generation_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'unknown canonical generation %', target_generation_id;
    END IF;
    IF target_state NOT IN ('READY', 'PUBLISHED', 'RETIRED') OR target_validated_at IS NULL THEN
        RAISE EXCEPTION 'generation % is not validated and publishable', target_generation_id;
    END IF;

    SELECT count(*)
      INTO physical_relation_count
      FROM pg_class relation
      JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
     WHERE namespace.nspname = target_schema
       AND relation.relkind = 'r'
       AND relation.relname = ANY (ARRAY[
            'systems', 'bodies', 'body_composition', 'body_alias',
            'body_parent_evidence', 'rings', 'body_signal_current',
            'body_genus_current', 'ring_signal_current', 'stations',
            'station_alias', 'station_placement', 'station_service_current',
            'station_economy_current'
       ]);
    IF physical_relation_count <> 14 THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = format(
                'generation %s physical schema %s is missing or incomplete',
                target_generation_id, target_schema
            );
    END IF;

    SELECT generation_id, publication_sequence
      INTO prior_generation_id, next_sequence
      FROM v3_meta.current_canonical_generation
     WHERE singleton
     FOR UPDATE;

    IF prior_generation_id = target_generation_id THEN
        RETURN next_sequence;
    END IF;

    next_sequence := COALESCE(next_sequence, 0) + 1;

    IF prior_generation_id IS NOT NULL THEN
        UPDATE v3_meta.canonical_generation
           SET lifecycle_state = 'RETIRED', retired_at = transaction_timestamp()
         WHERE generation_id = prior_generation_id;
    END IF;

    UPDATE v3_meta.canonical_generation
       SET lifecycle_state = 'PUBLISHED',
           published_at = COALESCE(published_at, transaction_timestamp()),
           retired_at = NULL
     WHERE generation_id = target_generation_id;

    INSERT INTO v3_meta.current_canonical_generation(
        singleton, generation_id, publication_sequence, published_at
    ) VALUES (
        true, target_generation_id, next_sequence, transaction_timestamp()
    )
    ON CONFLICT (singleton) DO UPDATE
       SET generation_id = EXCLUDED.generation_id,
           publication_sequence = EXCLUDED.publication_sequence,
           published_at = EXCLUDED.published_at;

    INSERT INTO v3_meta.canonical_publication_audit(
        publication_sequence, from_generation_id, to_generation_id,
        published_at, published_by, transaction_id, reason
    ) VALUES (
        next_sequence, prior_generation_id, target_generation_id,
        transaction_timestamp(), publication_actor, txid_current(), publication_reason
    );

    RETURN next_sequence;
END;
$function$;

COMMENT ON FUNCTION v3_meta.publish_canonical_generation(uuid, text, text) IS 'Transactional generation pointer publication/rollback. Candidate read relations must already be READY; no view DDL occurs.';

COMMIT;
