from __future__ import annotations

from typing import Any


SCHEMA_VERSION = 'evidence_sources/v1'


_SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        'source_name': 'canonical_app_data',
        'label': 'Canonical App Data',
        'site_url': None,
        'implementation_status': 'live',
        'current_usage': 'Lifecycle-managed evidence promotions derived from already-ingested canonical system, body, station, and ring tables.',
        'source_category': 'derived_source',
        'domains': ['systems', 'bodies', 'stations', 'rings'],
        'recommended_priority': 4,
        'ingestion_modes': ['canonical_snapshot_promotion'],
        'repo_surfaces': ['apps/api/src/evidence_store/store.py'],
        'why_this_matters': 'It turns known canonical coverage into inspectable evidence instead of leaving player trust surfaces at unknown.',
        'notes': 'Use only for derived evidence promotions from already-trusted canonical tables, not raw external ingestion.',
    },
    {
        'source_name': 'spansh',
        'label': 'Spansh',
        'site_url': 'https://spansh.co.uk/',
        'implementation_status': 'live',
        'current_usage': 'Bulk galaxy snapshots and delta imports for systems, bodies, stations, and rings.',
        'source_category': 'source_of_truth',
        'domains': ['systems', 'bodies', 'stations', 'rings'],
        'recommended_priority': 1,
        'ingestion_modes': ['nightly_bulk', 'delta_refresh'],
        'repo_surfaces': ['apps/importer/src/import_spansh.py', 'scripts/nightly_update.sh'],
        'why_this_matters': 'It remains the broadest practical backbone for canonical world-state coverage.',
        'notes': 'Already live and should stay the canonical baseline feed.',
    },
    {
        'source_name': 'eddn',
        'label': 'EDDN',
        'site_url': 'https://eddn.edcd.io/',
        'implementation_status': 'live',
        'current_usage': 'Live relay ingestion for new events, body scans, and dirty-system marking.',
        'source_category': 'source_of_truth',
        'domains': ['systems', 'bodies', 'rings', 'station_services', 'materials_resources'],
        'recommended_priority': 2,
        'ingestion_modes': ['streaming', 'event_capture'],
        'repo_surfaces': ['apps/eddn/src/eddn_listener.py', 'apps/api/src/ingest/eddn_client.py'],
        'why_this_matters': 'It gives the app freshness and closes the gap between nightly imports.',
        'notes': 'Best source for near-real-time evidence and freshness signals.',
    },
    {
        'source_name': 'edsm',
        'label': 'EDSM',
        'site_url': 'https://www.edsm.net/',
        'implementation_status': 'bounded_live',
        'current_usage': 'Bounded enrichment and staging for stations, bodies, and metadata reconciliation.',
        'source_category': 'source_of_evidence',
        'domains': ['stations', 'station_services', 'economies_security', 'bodies'],
        'recommended_priority': 3,
        'ingestion_modes': ['bounded_probe', 'staging_only', 'reviewed_apply'],
        'repo_surfaces': [
            'apps/importer/src/edsm_station_enrichment_probe.py',
            'apps/importer/src/edsm_station_import.py',
            'scripts/station_enrichment_guard.py',
        ],
        'why_this_matters': 'It is already partly wired and can expand coverage safely through staging-first provenance.',
        'notes': 'Good next source to productionise beyond bounded operator runs.',
    },
    {
        'source_name': 'inara',
        'label': 'Inara',
        'site_url': 'https://inara.cz/',
        'implementation_status': 'planned',
        'current_usage': 'No importer yet; intended for station services, markets, factions, and mission context enrichment.',
        'source_category': 'source_of_evidence',
        'domains': ['stations', 'station_services', 'markets', 'factions_bgs', 'mission_intelligence'],
        'recommended_priority': 4,
        'ingestion_modes': ['bounded_scrape_or_api', 'review_packet'],
        'repo_surfaces': ['docs/colonisation-redesign/stage-19-import-source-and-domain-matrix.md'],
        'why_this_matters': 'It is the highest-value missing enrichment surface once the evidence store is in place.',
        'notes': 'Implement only with clear rate limits, provenance, and legal/ToS review.',
    },
    {
        'source_name': 'frontier_journal',
        'label': 'Frontier Journal / Commander Logs',
        'site_url': 'https://www.elitedangerous.com/',
        'implementation_status': 'planned',
        'current_usage': 'No pipeline yet; intended for commander-local observations, mission evidence, and operator-submitted truth.',
        'source_category': 'source_of_evidence',
        'domains': ['mission_intelligence', 'construction_sites', 'station_services'],
        'recommended_priority': 5,
        'ingestion_modes': ['file_drop', 'operator_upload', 'edmc_bridge'],
        'repo_surfaces': [
            'docs/ROADMAP.md',
            'docs/colonisation-redesign/stage-19-import-source-and-domain-matrix.md',
        ],
        'why_this_matters': 'This is the cleanest path to first-party evidence the community feeds cannot guarantee.',
        'notes': 'Best foundation for future opt-in EDMC and EDDiscovery uploads.',
    },
    {
        'source_name': 'canonn',
        'label': 'Canonn Research',
        'site_url': 'https://canonn.science/',
        'implementation_status': 'planned',
        'current_usage': 'No importer yet; intended for curated research datasets and specialist discoveries.',
        'source_category': 'source_of_evidence',
        'domains': ['materials_resources', 'bodies', 'construction_sites'],
        'recommended_priority': 6,
        'ingestion_modes': ['periodic_snapshot', 'review_packet'],
        'repo_surfaces': ['docs/colonisation-redesign/stage-19-import-source-and-domain-matrix.md'],
        'why_this_matters': 'High-quality domain expertise can enrich niche discovery and colonisation signals.',
        'notes': 'Lower priority than Inara and journals because coverage is specialized rather than universal.',
    },
    {
        'source_name': 'edcd',
        'label': 'EDCD',
        'site_url': 'https://github.com/EDCD',
        'implementation_status': 'planned',
        'current_usage': 'No importer yet; intended for community-maintained reference datasets that complement EDDN.',
        'source_category': 'source_of_evidence',
        'domains': ['systems', 'stations', 'factions_bgs', 'economies_security'],
        'recommended_priority': 7,
        'ingestion_modes': ['periodic_snapshot'],
        'repo_surfaces': ['docs/colonisation-redesign/stage-19-import-source-and-domain-matrix.md'],
        'why_this_matters': 'It can supply stable reference enrichments where event streams are too sparse.',
        'notes': 'Treat as secondary to Spansh and EDDN, not a replacement.',
    },
    {
        'source_name': 'daftmav',
        'label': 'DaftMav',
        'site_url': 'https://www.daftmav.co.uk/',
        'implementation_status': 'live',
        'current_usage': 'Imports the colonisation workbook into facility-template catalogue JSON.',
        'source_category': 'source_of_inspiration',
        'domains': ['facility_templates'],
        'recommended_priority': 8,
        'ingestion_modes': ['manual_snapshot'],
        'repo_surfaces': ['apps/importer/src/import_facility_templates_from_daftmav.py'],
        'why_this_matters': 'Already useful for planner mechanics, but it is narrower than the missing evidence feeds.',
        'notes': 'Keep refreshed, but it is not the next expansion priority.',
    },
    {
        'source_name': 'ed_astrometrics',
        'label': 'ED Astrometrics',
        'site_url': 'https://edastro.com/',
        'implementation_status': 'planned',
        'current_usage': 'No importer yet; intended for POI data, regional statistics, and galaxy map enrichment.',
        'source_category': 'source_of_evidence',
        'domains': ['systems', 'bodies', 'exploration', 'galactic_mapping'],
        'recommended_priority': 5,
        'ingestion_modes': ['periodic_snapshot', 'api_probe'],
        'repo_surfaces': [],
        'why_this_matters': 'GEC/GMP POI database, regional statistics, and system API fill the exploration-narrative gap. 100 req/15min rate limit is generous.',
        'notes': 'REST API at edastro.com/api/starsystem. GEC POI API at edastro.com/gec. Galaxy map layers at edastro.com/galmap/.',
    },
    {
        'source_name': 'elite_bgs_api',
        'label': 'Elite BGS API',
        'site_url': 'https://elitebgs.app/',
        'implementation_status': 'planned',
        'current_usage': 'No importer yet; intended for faction influence history and BGS state timelines.',
        'source_category': 'source_of_evidence',
        'domains': ['factions_bgs', 'economies_security'],
        'recommended_priority': 6,
        'ingestion_modes': ['api_probe', 'periodic_snapshot'],
        'repo_surfaces': [],
        'why_this_matters': 'Faction influence history and state change timelines are essential for colonisation expansion strategy.',
        'notes': 'Built from nightly EDSM dumps. REST API for time-range queries by faction/system. GitHub: Elite-Kode/elitebgs.',
    },
    {
        'source_name': 'fdevids',
        'label': 'FDevIDs (Frontier ID Mappings)',
        'site_url': 'https://github.com/EDCD/FDevIDs',
        'implementation_status': 'planned',
        'current_usage': 'No importer yet; intended as reference dataset for commodity/station/ship ID lookups.',
        'source_category': 'source_of_evidence',
        'domains': ['systems', 'stations', 'markets', 'materials_resources'],
        'recommended_priority': 9,
        'ingestion_modes': ['periodic_snapshot'],
        'repo_surfaces': [],
        'why_this_matters': 'Essential for mapping Frontier internal commodity names (e.g. $aluminium_name;) to human-readable labels. Reference dataset maintained by EDCD.',
        'notes': 'Low update frequency (IDs rarely change). Import once, refresh quarterly.',
    },
]


def list_evidence_sources() -> list[dict[str, Any]]:
    return sorted(
        (dict(row) for row in _SOURCE_CATALOG),
        key=lambda row: (row['recommended_priority'], row['source_name']),
    )

