from __future__ import annotations

from typing import Any


REVIEW_SYSTEMS: tuple[dict[str, Any], ...] = (
    {
        'id64': 7200000000001,
        'name': 'Review Alpha',
        'x': 12.0,
        'y': 4.0,
        'z': 3.0,
        'primary_economy': 'HighTech',
        'secondary_economy': 'Refinery',
        'population': 4200000,
        'is_colonised': True,
        'security': 'High',
        'allegiance': 'Independent',
        'government': 'Democracy',
        'main_star_type': 'G',
        'main_star_subtype': '2 V',
        'body_count': 3,
        'rating': {
            'score': 91,
            'score_agriculture': 44,
            'score_refinery': 78,
            'score_industrial': 82,
            'score_hightech': 95,
            'score_military': 36,
            'score_tourism': 52,
            'score_extraction': 40,
            'economy_suggestion': 'HighTech',
            'elw_count': 1,
            'ww_count': 0,
            'ammonia_count': 0,
            'gas_giant_count': 1,
            'landable_count': 2,
            'terraformable_count': 1,
            'bio_signal_total': 4,
            'geo_signal_total': 6,
            'neutron_count': 0,
            'black_hole_count': 0,
            'white_dwarf_count': 0,
            'slots': 11,
            'body_quality': 82,
            'compactness': 74,
            'signal_quality': 79,
            'orbital_safety': 77,
            'star_bonus': 4,
            'confidence': 'review_fixture',
            'rating_version': 'review-fixture-v1',
            'rationale': 'Synthetic review fixture with strong planner-facing body data.',
            'score_breakdown': {
                'economy_fit': 40,
                'body_quality': 24,
                'signals': 15,
                'compactness': 8,
                'star_bonus': 4,
            },
        },
        'bodies': (
            {
                'id': 7200000000101,
                'name': 'Review Alpha',
                'body_type': 'Star',
                'subtype': 'G2 V',
                'is_main_star': True,
                'distance_from_star': 0.0,
                'radius': 695700.0,
                'mass': 1.0,
                'gravity': None,
                'surface_temp': 5778.0,
                'is_terraformable': False,
                'is_landable': False,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 0,
                'estimated_mapping_value': None,
                'estimated_scan_value': None,
                'spectral_class': 'G',
                'is_scoopable': True,
            },
            {
                'id': 7200000000102,
                'name': 'Review Alpha A 1',
                'body_type': 'Planet',
                'subtype': 'Earth-like world',
                'is_main_star': False,
                'distance_from_star': 11450.0,
                'radius': 6430.0,
                'mass': 1.03,
                'gravity': 9.8,
                'surface_temp': 287.0,
                'is_terraformable': True,
                'is_landable': False,
                'is_water_world': False,
                'is_earth_like': True,
                'is_ammonia_world': False,
                'bio_signal_count': 4,
                'geo_signal_count': 0,
                'estimated_mapping_value': 1450000,
                'estimated_scan_value': 380000,
                'spectral_class': None,
                'is_scoopable': None,
            },
            {
                'id': 7200000000103,
                'name': 'Review Alpha A 2',
                'body_type': 'Planet',
                'subtype': 'High metal content body',
                'is_main_star': False,
                'distance_from_star': 28400.0,
                'radius': 5100.0,
                'mass': 0.81,
                'gravity': 7.4,
                'surface_temp': 410.0,
                'is_terraformable': False,
                'is_landable': True,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 6,
                'estimated_mapping_value': 210000,
                'estimated_scan_value': 54000,
                'spectral_class': None,
                'is_scoopable': None,
            },
        ),
        'stations': (
            {
                'id': 7200000000201,
                'name': 'Alpha Prospect',
                'station_type': 'Coriolis',
                'distance_from_star': 310.0,
                'body_name': 'Review Alpha A 1',
                'landing_pad_size': 'L',
                'primary_economy': 'HighTech',
                'secondary_economy': 'Refinery',
                'has_market': True,
                'has_shipyard': True,
                'has_outfitting': True,
                'has_refuel': True,
                'has_repair': True,
                'has_rearm': True,
                'allegiance': 'Independent',
                'government': 'Democracy',
            },
        ),
    },
    {
        'id64': 7200000000002,
        'name': 'Review Beta',
        'x': 18.0,
        'y': -5.0,
        'z': 7.0,
        'primary_economy': 'Refinery',
        'secondary_economy': 'Extraction',
        'population': 0,
        'is_colonised': False,
        'security': 'Low',
        'allegiance': 'Independent',
        'government': 'None',
        'main_star_type': 'K',
        'main_star_subtype': '4 V',
        'body_count': 2,
        'rating': {
            'score': 76,
            'score_agriculture': 38,
            'score_refinery': 88,
            'score_industrial': 58,
            'score_hightech': 41,
            'score_military': 30,
            'score_tourism': 34,
            'score_extraction': 70,
            'economy_suggestion': 'Refinery',
            'elw_count': 0,
            'ww_count': 0,
            'ammonia_count': 0,
            'gas_giant_count': 1,
            'landable_count': 1,
            'terraformable_count': 0,
            'bio_signal_total': 0,
            'geo_signal_total': 2,
            'neutron_count': 0,
            'black_hole_count': 0,
            'white_dwarf_count': 0,
            'slots': 7,
            'body_quality': 61,
            'compactness': 69,
            'signal_quality': 35,
            'orbital_safety': 73,
            'star_bonus': 3,
            'confidence': 'review_fixture',
            'rating_version': 'review-fixture-v1',
            'rationale': 'Synthetic review fixture with enough structure for the planner workspace.',
            'score_breakdown': {
                'economy_fit': 36,
                'body_quality': 16,
                'signals': 6,
                'compactness': 10,
                'star_bonus': 3,
            },
        },
        'bodies': (
            {
                'id': 7200000000301,
                'name': 'Review Beta',
                'body_type': 'Star',
                'subtype': 'K4 V',
                'is_main_star': True,
                'distance_from_star': 0.0,
                'radius': 480000.0,
                'mass': 0.72,
                'gravity': None,
                'surface_temp': 4400.0,
                'is_terraformable': False,
                'is_landable': False,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 0,
                'estimated_mapping_value': None,
                'estimated_scan_value': None,
                'spectral_class': 'K',
                'is_scoopable': True,
            },
            {
                'id': 7200000000302,
                'name': 'Review Beta A 1',
                'body_type': 'Planet',
                'subtype': 'Rocky body',
                'is_main_star': False,
                'distance_from_star': 16200.0,
                'radius': 3900.0,
                'mass': 0.43,
                'gravity': 5.7,
                'surface_temp': 302.0,
                'is_terraformable': False,
                'is_landable': True,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 2,
                'estimated_mapping_value': 98000,
                'estimated_scan_value': 31000,
                'spectral_class': None,
                'is_scoopable': None,
            },
        ),
        'stations': (
            {
                'id': 7200000000401,
                'name': 'Beta Assembly',
                'station_type': 'Outpost',
                'distance_from_star': 540.0,
                'body_name': 'Review Beta A 1',
                'landing_pad_size': 'M',
                'primary_economy': 'Refinery',
                'secondary_economy': 'Extraction',
                'has_market': True,
                'has_shipyard': False,
                'has_outfitting': True,
                'has_refuel': True,
                'has_repair': True,
                'has_rearm': True,
                'allegiance': 'Independent',
                'government': 'None',
            },
        ),
    },
    {
        'id64': 7200000000003,
        'name': 'Review Gamma',
        'x': 24.0,
        'y': 9.0,
        'z': -6.0,
        'primary_economy': 'Agriculture',
        'secondary_economy': 'Tourism',
        'population': 1380000,
        'is_colonised': True,
        'security': 'Medium',
        'allegiance': 'Alliance',
        'government': 'Democracy',
        'main_star_type': 'F',
        'main_star_subtype': '7 V',
        'body_count': 3,
        'rating': {
            'score': 84,
            'score_agriculture': 93,
            'score_refinery': 46,
            'score_industrial': 49,
            'score_hightech': 54,
            'score_military': 28,
            'score_tourism': 79,
            'score_extraction': 27,
            'economy_suggestion': 'Agriculture',
            'elw_count': 0,
            'ww_count': 1,
            'ammonia_count': 0,
            'gas_giant_count': 1,
            'landable_count': 2,
            'terraformable_count': 1,
            'bio_signal_total': 3,
            'geo_signal_total': 4,
            'neutron_count': 0,
            'black_hole_count': 0,
            'white_dwarf_count': 0,
            'slots': 8,
            'body_quality': 73,
            'compactness': 71,
            'signal_quality': 66,
            'orbital_safety': 74,
            'star_bonus': 3,
            'confidence': 'review_fixture',
            'rating_version': 'review-fixture-v1',
            'rationale': 'Synthetic review fixture with mixed body types and a stable station layout.',
            'score_breakdown': {
                'economy_fit': 34,
                'body_quality': 20,
                'signals': 12,
                'compactness': 9,
                'star_bonus': 3,
            },
        },
        'bodies': (
            {
                'id': 7200000000501,
                'name': 'Review Gamma',
                'body_type': 'Star',
                'subtype': 'F7 V',
                'is_main_star': True,
                'distance_from_star': 0.0,
                'radius': 760000.0,
                'mass': 1.18,
                'gravity': None,
                'surface_temp': 6250.0,
                'is_terraformable': False,
                'is_landable': False,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 0,
                'estimated_mapping_value': None,
                'estimated_scan_value': None,
                'spectral_class': 'F',
                'is_scoopable': True,
            },
            {
                'id': 7200000000502,
                'name': 'Review Gamma A 1',
                'body_type': 'Planet',
                'subtype': 'Water world',
                'is_main_star': False,
                'distance_from_star': 13600.0,
                'radius': 7010.0,
                'mass': 1.15,
                'gravity': 10.1,
                'surface_temp': 290.0,
                'is_terraformable': True,
                'is_landable': False,
                'is_water_world': True,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 3,
                'geo_signal_count': 0,
                'estimated_mapping_value': 870000,
                'estimated_scan_value': 240000,
                'spectral_class': None,
                'is_scoopable': None,
            },
            {
                'id': 7200000000503,
                'name': 'Review Gamma A 2',
                'body_type': 'Planet',
                'subtype': 'Rocky ice body',
                'is_main_star': False,
                'distance_from_star': 33200.0,
                'radius': 2900.0,
                'mass': 0.24,
                'gravity': 3.6,
                'surface_temp': 180.0,
                'is_terraformable': False,
                'is_landable': True,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 4,
                'estimated_mapping_value': 74000,
                'estimated_scan_value': 24000,
                'spectral_class': None,
                'is_scoopable': None,
            },
        ),
        'stations': (
            {
                'id': 7200000000601,
                'name': 'Gamma Habitat',
                'station_type': 'Orbis',
                'distance_from_star': 280.0,
                'body_name': 'Review Gamma A 1',
                'landing_pad_size': 'L',
                'primary_economy': 'Agriculture',
                'secondary_economy': 'Tourism',
                'has_market': True,
                'has_shipyard': True,
                'has_outfitting': True,
                'has_refuel': True,
                'has_repair': True,
                'has_rearm': True,
                'allegiance': 'Alliance',
                'government': 'Democracy',
            },
        ),
    },
    {
        'id64': 7200000000004,
        'name': 'Review Delta',
        'x': 31.0,
        'y': -11.0,
        'z': 12.0,
        'primary_economy': 'Industrial',
        'secondary_economy': 'HighTech',
        'population': 5700000,
        'is_colonised': True,
        'security': 'High',
        'allegiance': 'Federation',
        'government': 'Corporate',
        'main_star_type': 'A',
        'main_star_subtype': '8 V',
        'body_count': 2,
        'rating': {
            'score': 88,
            'score_agriculture': 32,
            'score_refinery': 64,
            'score_industrial': 94,
            'score_hightech': 86,
            'score_military': 45,
            'score_tourism': 39,
            'score_extraction': 41,
            'economy_suggestion': 'Industrial',
            'elw_count': 0,
            'ww_count': 0,
            'ammonia_count': 0,
            'gas_giant_count': 1,
            'landable_count': 1,
            'terraformable_count': 0,
            'bio_signal_total': 0,
            'geo_signal_total': 3,
            'neutron_count': 0,
            'black_hole_count': 0,
            'white_dwarf_count': 0,
            'slots': 9,
            'body_quality': 70,
            'compactness': 77,
            'signal_quality': 48,
            'orbital_safety': 80,
            'star_bonus': 4,
            'confidence': 'review_fixture',
            'rating_version': 'review-fixture-v1',
            'rationale': 'Synthetic review fixture reserved for not-evaluated evidence and provenance fallback.',
            'score_breakdown': {
                'economy_fit': 37,
                'body_quality': 18,
                'signals': 8,
                'compactness': 11,
                'star_bonus': 4,
            },
        },
        'bodies': (
            {
                'id': 7200000000701,
                'name': 'Review Delta',
                'body_type': 'Star',
                'subtype': 'A8 V',
                'is_main_star': True,
                'distance_from_star': 0.0,
                'radius': 1040000.0,
                'mass': 1.65,
                'gravity': None,
                'surface_temp': 7550.0,
                'is_terraformable': False,
                'is_landable': False,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 0,
                'estimated_mapping_value': None,
                'estimated_scan_value': None,
                'spectral_class': 'A',
                'is_scoopable': True,
            },
            {
                'id': 7200000000702,
                'name': 'Review Delta A 1',
                'body_type': 'Planet',
                'subtype': 'High metal content body',
                'is_main_star': False,
                'distance_from_star': 11900.0,
                'radius': 4600.0,
                'mass': 0.72,
                'gravity': 7.9,
                'surface_temp': 350.0,
                'is_terraformable': False,
                'is_landable': True,
                'is_water_world': False,
                'is_earth_like': False,
                'is_ammonia_world': False,
                'bio_signal_count': 0,
                'geo_signal_count': 3,
                'estimated_mapping_value': 118000,
                'estimated_scan_value': 36000,
                'spectral_class': None,
                'is_scoopable': None,
            },
        ),
        'stations': (
            {
                'id': 7200000000801,
                'name': 'Delta Foundry',
                'station_type': 'Coriolis',
                'distance_from_star': 260.0,
                'body_name': 'Review Delta A 1',
                'landing_pad_size': 'L',
                'primary_economy': 'Industrial',
                'secondary_economy': 'HighTech',
                'has_market': True,
                'has_shipyard': True,
                'has_outfitting': True,
                'has_refuel': True,
                'has_repair': True,
                'has_rearm': True,
                'allegiance': 'Federation',
                'government': 'Corporate',
            },
        ),
    },
)


REVIEW_SYSTEM_BY_ID = {system['id64']: system for system in REVIEW_SYSTEMS}


def review_warehouse_contract_key(id64: int) -> str:
    return f'review_environment.warehouse_contract.{id64}'


def review_provenance_contract_key(id64: int) -> str:
    return f'review_environment.provenance_contract.{id64}'


_UNKNOWN_WAREHOUSE_COVERAGE: dict[str, Any] = {
    'body_scan': {
        'status': 'unknown',
        'known_count': None,
        'total_count': None,
        'coverage_ratio': None,
        'summary': 'Review fixture coverage is intentionally synthetic and unknown.',
    },
    'station_links': {
        'status': 'unknown',
        'known_count': None,
        'total_count': None,
        'coverage_ratio': None,
        'summary': 'Review fixture station-link coverage is intentionally synthetic and unknown.',
    },
    'ring_identity': {
        'status': 'unknown',
        'known_count': None,
        'total_count': None,
        'coverage_ratio': None,
        'summary': 'Review fixture ring-identity coverage is intentionally synthetic and unknown.',
    },
    'source_freshness': {
        'canonical_updated_at': None,
        'observed_updated_at': None,
        'bounded_staging_updated_at': None,
        'status_updated_at': None,
    },
    'thin_data_reasons': [
        'Review fixtures are report-only synthetic scenarios and do not claim full selected-system coverage.',
    ],
    'summary': 'Review fixture coverage remains synthetic, report-only, and not full coverage.',
}


REVIEW_WAREHOUSE_CONTRACTS: dict[int, dict[str, Any]] = {
    7200000000001: {
        'schema_version': 'warehouse_planner_evidence/v1',
        'system_id64': 7200000000001,
        'generated_at': '2026-06-21T12:00:00Z',
        'freshness': {
            'status': 'fresh',
            'evaluated_at': '2026-06-21T12:00:00Z',
        },
        'source_run': {
            'source_name': 'review_fixture',
            'run_key': 'review-fixture/review-alpha-evidence',
        },
        'evidence_envelope': {
            'status': 'available',
            'source_classes': ['canonical', 'bounded_staging', 'derived_report'],
            'semantics': [
                'canonical_truth',
                'bounded_staging_evidence',
                'report_only_review_context',
                'not_full_coverage',
            ],
            'report_only': True,
            'selected_system_only': True,
            'planner_truth_source_class': 'canonical',
            'claims_canonical_truth': False,
            'claims_full_coverage': False,
            'summary': 'Canonical planner data remains the planner truth source; review-only supporting evidence is report-only and bounded.',
        },
        'bounded_staging': {
            'status': 'available',
            'report_only': True,
            'bounded_staging_only': True,
            'source_name': 'review_fixture',
            'source_batch_label': 'review-alpha-window-25',
            'source_sha256': 'review-alpha-not-canonical',
            'source_run_key': 'review-fixture/review-alpha-bounded-staging',
            'bridge_key': 'source_runs:review-fixture/review-alpha-bounded-staging',
            'row_limit': 25,
            'available_row_limits': [25, 100],
            'matched_row_count': 3,
            'latest_source_updated_at': '2026-06-21T12:00:00Z',
            'summary': 'Bounded staging covers only a review-only 25-row window and is not full coverage.',
        },
        'coverage': _UNKNOWN_WAREHOUSE_COVERAGE,
        'evidence_summary': {
            'availability': 'report_only',
            'report_only': True,
            'manual_review_required': True,
            'items': [
                {
                    'label': 'report_only',
                    'source': 'canonical',
                    'summary': 'Canonical planner data is available and remains the planner truth source for Review Alpha.',
                },
                {
                    'label': 'report_only',
                    'source': 'warehouse_report_only',
                    'summary': 'Supporting evidence is synthetic, review-only, and explicitly non-canonical.',
                },
                {
                    'label': 'needs_review',
                    'source': 'warehouse_report_only',
                    'summary': 'Coverage is bounded and incomplete, so manual review remains required.',
                },
            ],
        },
        'warnings': [
            'Review Alpha evidence is synthetic review-only context and never canonical truth.',
        ],
    },
    7200000000002: {
        'schema_version': 'warehouse_planner_evidence/v1',
        'system_id64': 7200000000002,
        'generated_at': '2026-06-21T12:05:00Z',
        'freshness': {
            'status': 'unknown',
            'evaluated_at': None,
        },
        'source_run': {
            'source_name': 'review_fixture',
            'run_key': 'review-fixture/review-beta-evidence',
        },
        'evidence_envelope': {
            'status': 'unavailable',
            'source_classes': ['unavailable'],
            'semantics': ['report_only_review_context'],
            'report_only': True,
            'selected_system_only': True,
            'planner_truth_source_class': 'unavailable',
            'claims_canonical_truth': False,
            'claims_full_coverage': False,
            'summary': 'Selected-system evidence is intentionally unavailable for Review Beta.',
        },
        'bounded_staging': {
            'status': 'unavailable',
            'report_only': True,
            'bounded_staging_only': True,
            'source_name': 'review_fixture',
            'source_batch_label': None,
            'source_sha256': None,
            'source_run_key': None,
            'bridge_key': None,
            'row_limit': None,
            'available_row_limits': [],
            'matched_row_count': None,
            'latest_source_updated_at': None,
            'summary': 'No selected-system review evidence is linked for Review Beta.',
        },
        'coverage': _UNKNOWN_WAREHOUSE_COVERAGE,
        'evidence_summary': {
            'availability': 'unavailable',
            'report_only': True,
            'manual_review_required': False,
            'items': [],
        },
        'warnings': [
            'Review Beta is intentionally configured with unavailable selected-system evidence.',
        ],
    },
    7200000000003: {
        'schema_version': 'warehouse_planner_evidence/v1',
        'system_id64': 7200000000003,
        'generated_at': '2026-06-21T12:10:00Z',
        'freshness': {
            'status': 'unknown',
            'evaluated_at': None,
        },
        'source_run': {
            'source_name': 'review_fixture',
            'run_key': 'review-fixture/review-gamma-evidence',
        },
        'evidence_envelope': {
            'status': 'unknown',
            'source_classes': ['derived_report'],
            'semantics': ['report_only_review_context'],
            'report_only': True,
            'selected_system_only': True,
            'planner_truth_source_class': 'canonical',
            'claims_canonical_truth': False,
            'claims_full_coverage': False,
            'summary': 'Selected-system evidence remains unknown for Review Gamma and stays technically unknown.',
        },
        'bounded_staging': {
            'status': 'not_evaluated',
            'report_only': True,
            'bounded_staging_only': True,
            'source_name': 'review_fixture',
            'source_batch_label': None,
            'source_sha256': None,
            'source_run_key': None,
            'bridge_key': None,
            'row_limit': None,
            'available_row_limits': [],
            'matched_row_count': None,
            'latest_source_updated_at': None,
            'summary': 'Bounded staging is not evaluated for Review Gamma.',
        },
        'coverage': _UNKNOWN_WAREHOUSE_COVERAGE,
        'evidence_summary': {
            'availability': 'report_only',
            'report_only': True,
            'manual_review_required': True,
            'items': [
                {
                    'label': 'unknown',
                    'source': 'unknown',
                    'summary': 'Evidence linkage is intentionally unknown for this review-only scenario.',
                },
            ],
        },
        'warnings': [
            'Review Gamma preserves the player-facing unknown evidence posture.',
        ],
    },
    7200000000004: {
        'schema_version': 'warehouse_planner_evidence/v1',
        'system_id64': 7200000000004,
        'generated_at': '2026-06-21T12:15:00Z',
        'freshness': {
            'status': 'not_evaluated',
            'evaluated_at': None,
        },
        'source_run': {
            'source_name': 'review_fixture',
            'run_key': 'review-fixture/review-delta-evidence',
        },
        'evidence_envelope': {
            'status': 'not_evaluated',
            'source_classes': ['derived_report'],
            'semantics': ['report_only_review_context'],
            'report_only': True,
            'selected_system_only': True,
            'planner_truth_source_class': 'canonical',
            'claims_canonical_truth': False,
            'claims_full_coverage': False,
            'summary': 'Selected-system evidence is intentionally not evaluated for Review Delta.',
        },
        'bounded_staging': {
            'status': 'not_evaluated',
            'report_only': True,
            'bounded_staging_only': True,
            'source_name': 'review_fixture',
            'source_batch_label': None,
            'source_sha256': None,
            'source_run_key': None,
            'bridge_key': None,
            'row_limit': None,
            'available_row_limits': [],
            'matched_row_count': None,
            'latest_source_updated_at': None,
            'summary': 'Bounded staging is intentionally not evaluated for Review Delta.',
        },
        'coverage': _UNKNOWN_WAREHOUSE_COVERAGE,
        'evidence_summary': {
            'availability': 'report_only',
            'report_only': True,
            'manual_review_required': True,
            'items': [
                {
                    'label': 'blocked',
                    'source': 'warehouse_report_only',
                    'summary': 'This review-only case keeps the evidence path not evaluated for acceptance coverage.',
                },
            ],
        },
        'warnings': [
            'Review Delta is intentionally configured with a not-evaluated evidence path.',
        ],
    },
}


REVIEW_PROVENANCE_CONTRACTS: dict[int, dict[str, Any]] = {
    7200000000001: {
        'schema_version': 'stage20a_provenance_cockpit/v1',
        'system': {
            'id64': 7200000000001,
            'name': 'Review Alpha',
            'primary_archetype': 'hightech_refinery',
        },
        'provenance_summary': {
            'state': 'available',
            'latest_source_run_key': 'review-fixture/review-alpha-provenance',
            'warehouse_state': 'available',
            'planner_evidence_state': 'available',
        },
        'evidence_panels': {
            'source_run': {
                'state': 'available',
                'source_name': 'review_fixture',
                'rows_read': 25,
                'rows_staged': 25,
                'artifact_name': 'review-alpha-provenance.json',
            },
            'warehouse': {
                'state': 'available',
                'report_only': True,
                'canonical_writes_planned': 0,
                'stale_records': 0,
            },
            'planner': {
                'state': 'available',
                'observed_facts_count': 2,
                'projected_build_count': 1,
                'manual_review_required': True,
            },
        },
        'guardrails': {
            'stage19_paused': True,
            'stage19_production_activation_complete': False,
            'next_stage19_write_lane_authorized': False,
            'canonical_apply_complete': False,
            'rebaseline_complete': False,
            'scheduler_enabled': False,
            'db_writes_authorized': False,
            'stage19_operator_commands_authorized': False,
        },
        'warnings': [
            'Review Alpha provenance is synthetic review-only context; canonical planner data remains the planner truth source.',
        ],
        'ui_hints': {
            'severity': 'info',
            'empty_state_key': None,
        },
    },
    7200000000002: {
        'schema_version': 'stage20a_provenance_cockpit/v1',
        'system': {
            'id64': 7200000000002,
            'name': 'Review Beta',
            'primary_archetype': 'refinery_extraction',
        },
        'provenance_summary': {
            'state': 'unknown',
            'latest_source_run_key': None,
            'warehouse_state': 'unknown',
            'planner_evidence_state': 'unknown',
        },
        'evidence_panels': {
            'source_run': {
                'state': 'unknown',
                'source_name': 'review_fixture',
                'rows_read': None,
                'rows_staged': None,
                'artifact_name': None,
            },
            'warehouse': {
                'state': 'unknown',
                'report_only': True,
                'canonical_writes_planned': 0,
                'stale_records': 0,
            },
            'planner': {
                'state': 'unknown',
                'observed_facts_count': 0,
                'projected_build_count': 0,
                'manual_review_required': False,
            },
        },
        'guardrails': {
            'stage19_paused': True,
            'stage19_production_activation_complete': False,
            'next_stage19_write_lane_authorized': False,
            'canonical_apply_complete': False,
            'rebaseline_complete': False,
            'scheduler_enabled': False,
            'db_writes_authorized': False,
            'stage19_operator_commands_authorized': False,
        },
        'warnings': [
            'Review Beta keeps the provenance fallback in an unknown state for review-only coverage.',
        ],
        'ui_hints': {
            'severity': 'warning',
            'empty_state_key': 'review-beta-provenance-unavailable',
        },
    },
    7200000000003: {
        'schema_version': 'stage20a_provenance_cockpit/v1',
        'system': {
            'id64': 7200000000003,
            'name': 'Review Gamma',
            'primary_archetype': 'agriculture_tourism',
        },
        'provenance_summary': {
            'state': 'unknown',
            'latest_source_run_key': None,
            'warehouse_state': 'unknown',
            'planner_evidence_state': 'unknown',
        },
        'evidence_panels': {
            'source_run': {
                'state': 'unknown',
                'source_name': 'review_fixture',
                'rows_read': None,
                'rows_staged': None,
                'artifact_name': None,
            },
            'warehouse': {
                'state': 'unknown',
                'report_only': True,
                'canonical_writes_planned': 0,
                'stale_records': 0,
            },
            'planner': {
                'state': 'unknown',
                'observed_facts_count': 0,
                'projected_build_count': 0,
                'manual_review_required': True,
            },
        },
        'guardrails': {
            'stage19_paused': True,
            'stage19_production_activation_complete': False,
            'next_stage19_write_lane_authorized': False,
            'canonical_apply_complete': False,
            'rebaseline_complete': False,
            'scheduler_enabled': False,
            'db_writes_authorized': False,
            'stage19_operator_commands_authorized': False,
        },
        'warnings': [
            'Review Gamma intentionally keeps provenance unknown to preserve the player-facing unknown state.',
        ],
        'ui_hints': {
            'severity': 'neutral',
            'empty_state_key': 'review-gamma-provenance-unknown',
        },
    },
    7200000000004: {
        'schema_version': 'stage20a_provenance_cockpit/v1',
        'system': {
            'id64': 7200000000004,
            'name': 'Review Delta',
            'primary_archetype': 'industrial_hightech',
        },
        'provenance_summary': {
            'state': 'unknown',
            'latest_source_run_key': None,
            'warehouse_state': 'unknown',
            'planner_evidence_state': 'unknown',
        },
        'evidence_panels': {
            'source_run': {
                'state': 'unknown',
                'source_name': 'review_fixture',
                'rows_read': None,
                'rows_staged': None,
                'artifact_name': None,
            },
            'warehouse': {
                'state': 'unknown',
                'report_only': True,
                'canonical_writes_planned': 0,
                'stale_records': 0,
            },
            'planner': {
                'state': 'unknown',
                'observed_facts_count': 0,
                'projected_build_count': 0,
                'manual_review_required': True,
            },
        },
        'guardrails': {
            'stage19_paused': True,
            'stage19_production_activation_complete': False,
            'next_stage19_write_lane_authorized': False,
            'canonical_apply_complete': False,
            'rebaseline_complete': False,
            'scheduler_enabled': False,
            'db_writes_authorized': False,
            'stage19_operator_commands_authorized': False,
        },
        'warnings': [
            'Review Delta exercises the provenance fallback while planner evidence remains not evaluated.',
        ],
        'ui_hints': {
            'severity': 'neutral',
            'empty_state_key': 'review-delta-provenance-fallback',
        },
    },
}


REQUIRED_REVIEW_SYSTEM_NAMES = tuple(system['name'] for system in REVIEW_SYSTEMS)
