"""
ED Finder — Simulation: CP Simulator
======================================
Models construction-point (CP) economics for a colony build.

Design rules:
  • Pure functions + dataclasses — no DB, no asyncio.
  • Deterministic: same inputs → same outputs.
  • Explainable: every CP decision is traced.

CP mechanics (community-derived, confidence: observed):
  Yellow CP = standard colonisation points generated by facilities.
  Green CP  = bonus points from specific facility combinations.

  T2 ports cost CPs to unlock. T3 ports cost significantly more.
  The CP budget is determined by the total CP generated by all
  support facilities minus the CP consumed by port placements.

  Escalating costs: each additional T2/T3 port costs progressively more.
  This means the first T2 is cheap; the 5th T2 is expensive.

  IMPORTANT: Exact escalation curves are NOT publicly documented by
  Frontier. The values below are community estimates with moderate
  confidence. Mark in stat_effects on facility rows when confirmed.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from edfinder_api.domain.facilities import FacilityTemplate
from edfinder_api.mechanics.cp_rules import (
    CP_COMPLEXITY_THRESHOLDS,
    T2_GREEN_EXTRAPOLATION_STEP,
    T2_PORT_COSTS_GREEN,
    T2_PORT_COSTS_YELLOW,
    T2_YELLOW_EXTRAPOLATION_STEP,
    T3_GREEN_EXTRAPOLATION_STEP,
    T3_PORT_COSTS_GREEN,
    T3_PORT_COSTS_YELLOW,
    T3_YELLOW_EXTRAPOLATION_STEP,
)


# ---------------------------------------------------------------------------
# CP escalation curves (community estimates)
# Indexed by port count (0-based): cost of the Nth port of that tier.
# ---------------------------------------------------------------------------
_T2_PORT_COSTS_YELLOW = T2_PORT_COSTS_YELLOW
_T3_PORT_COSTS_YELLOW = T3_PORT_COSTS_YELLOW
_T2_PORT_COSTS_GREEN = T2_PORT_COSTS_GREEN
_T3_PORT_COSTS_GREEN = T3_PORT_COSTS_GREEN

# Complexity thresholds
_COMPLEXITY_THRESHOLDS = CP_COMPLEXITY_THRESHOLDS


@dataclass
class CPState:
    """
    Running CP budget during a simulation.

    Tracks generated and consumed CPs separately to produce
    clear bottleneck analysis.
    """
    yellow_generated: int = 0
    green_generated:  int = 0
    yellow_consumed:  int = 0
    green_consumed:   int = 0

    t2_ports_placed:  int = 0
    t3_ports_placed:  int = 0

    history: list[dict] = field(default_factory=list)

    @property
    def yellow_available(self) -> int:
        return max(0, self.yellow_generated - self.yellow_consumed)

    @property
    def green_available(self) -> int:
        return max(0, self.green_generated - self.green_consumed)

    @property
    def total_generated(self) -> int:
        return self.yellow_generated + self.green_generated

    @property
    def total_consumed(self) -> int:
        return self.yellow_consumed + self.green_consumed

    def add_facility(self, facility: FacilityTemplate, step: int = 0) -> None:
        """Register CP contribution from a placed facility."""
        if facility.yellow_cp_generated > 0 or facility.green_cp_generated > 0:
            self.yellow_generated += facility.yellow_cp_generated
            self.green_generated  += facility.green_cp_generated
            self.history.append({
                'step':     step,
                'action':   'generate',
                'facility': facility.id,
                'yellow':   facility.yellow_cp_generated,
                'green':    facility.green_cp_generated,
            })

    def place_port(
        self,
        facility: FacilityTemplate,
        step: int = 0,
    ) -> 'CPPlacementResult':
        """
        Attempt to place a port, consuming the appropriate escalating CP cost.
        Returns a result indicating success and the cost paid.
        """
        if facility.tier == 3:
            yellow_cost = _t3_yellow_cost(self.t3_ports_placed)
            green_cost  = _t3_green_cost(self.t3_ports_placed)
        elif facility.tier == 2:
            yellow_cost = _t2_yellow_cost(self.t2_ports_placed)
            green_cost  = _t2_green_cost(self.t2_ports_placed)
        else:
            # T1 ports (colony ship etc.) have no CP cost
            yellow_cost = facility.yellow_cp_cost
            green_cost  = facility.green_cp_cost

        can_afford = (
            self.yellow_available >= yellow_cost
            and self.green_available >= green_cost
        )

        if can_afford:
            self.yellow_consumed += yellow_cost
            self.green_consumed  += green_cost
            if facility.tier == 3:
                self.t3_ports_placed += 1
            elif facility.tier == 2:
                self.t2_ports_placed += 1

            self.history.append({
                'step':         step,
                'action':       'place_port',
                'facility':     facility.id,
                'yellow_cost':  yellow_cost,
                'green_cost':   green_cost,
                'yellow_after': self.yellow_available,
                'green_after':  self.green_available,
            })

        return CPPlacementResult(
            success=can_afford,
            yellow_cost=yellow_cost,
            green_cost=green_cost,
            yellow_shortfall=max(0, yellow_cost - self.yellow_available) if not can_afford else 0,
            green_shortfall=max(0, green_cost - self.green_available) if not can_afford else 0,
        )

    def next_t2_cost(self) -> tuple[int, int]:
        """Cost (yellow, green) of the next T2 port."""
        return _t2_yellow_cost(self.t2_ports_placed), _t2_green_cost(self.t2_ports_placed)

    def next_t3_cost(self) -> tuple[int, int]:
        """Cost (yellow, green) of the next T3 port."""
        return _t3_yellow_cost(self.t3_ports_placed), _t3_green_cost(self.t3_ports_placed)

    def to_dict(self) -> dict:
        return {
            'yellow_generated':  self.yellow_generated,
            'green_generated':   self.green_generated,
            'yellow_consumed':   self.yellow_consumed,
            'green_consumed':    self.green_consumed,
            'yellow_available':  self.yellow_available,
            'green_available':   self.green_available,
            'total_generated':   self.total_generated,
            'total_consumed':    self.total_consumed,
            't2_ports_placed':   self.t2_ports_placed,
            't3_ports_placed':   self.t3_ports_placed,
        }


@dataclass
class CPPlacementResult:
    success:           bool
    yellow_cost:       int
    green_cost:        int
    yellow_shortfall:  int = 0
    green_shortfall:   int = 0


@dataclass
class CPAnalysis:
    """
    Output of analyse_cp_budget().
    Summarises CP capacity, port potential, and bottleneck risk.
    """
    yellow_generated:          int
    green_generated:           int
    max_t2_ports_affordable:   int
    max_t3_ports_affordable:   int
    cp_bottleneck_score:       float   # 0–100; high = CP is limiting factor
    bottlenecks:               list[dict]
    opportunities:             list[dict]
    recommended_facility_order: list[str]   # facility_ids in recommended sequence

    def to_dict(self) -> dict:
        return {
            'yellow_generated':           self.yellow_generated,
            'green_generated':            self.green_generated,
            'max_t2_ports_affordable':    self.max_t2_ports_affordable,
            'max_t3_ports_affordable':    self.max_t3_ports_affordable,
            'cp_bottleneck_score':        round(self.cp_bottleneck_score, 1),
            'bottlenecks':                self.bottlenecks,
            'opportunities':              self.opportunities,
            'recommended_facility_order': self.recommended_facility_order,
        }


def analyse_cp_budget(
    facilities: list[FacilityTemplate],
    orbital_slots: int,
    surface_slots: int,
    has_ringed_body: bool = False,
) -> CPAnalysis:
    """
    Simulate CP generation and consumption for a set of facilities,
    determine port capacity, and identify bottlenecks.

    This is the main entry point for CP analysis.
    """
    # Build CP state from all support facilities
    state = CPState()
    for i, f in enumerate(facilities):
        if not f.is_port:
            state.add_facility(f, step=i + 1)

    # Simulate placing T2 ports until we run out of CP or slots
    sim_state = CPState()
    sim_state.yellow_generated = state.yellow_generated
    sim_state.green_generated  = state.green_generated

    t2_affordable = 0
    available_slots = orbital_slots + surface_slots
    while t2_affordable < available_slots:
        result = sim_state.place_port(
            _dummy_t2_port(), step=t2_affordable + 1
        )
        if not result.success:
            break
        t2_affordable += 1

    # Simulate T3 (reset and try — T3 costs more but replaces T2)
    sim_state_t3 = CPState()
    sim_state_t3.yellow_generated = state.yellow_generated
    sim_state_t3.green_generated  = state.green_generated

    t3_affordable = 0
    while t3_affordable < min(orbital_slots, 4):  # T3s only go orbital
        result = sim_state_t3.place_port(
            _dummy_t3_port(), step=t3_affordable + 1
        )
        if not result.success:
            break
        t3_affordable += 1

    # ── Bottleneck scoring ────────────────────────────────────────────────
    bottlenecks: list[dict] = []
    opportunities: list[dict] = []

    total_slots = orbital_slots + surface_slots

    # CP bottleneck: can we not afford as many ports as we have slots?
    if t2_affordable < total_slots:
        shortfall = total_slots - t2_affordable
        bottlenecks.append({
            'type':     'cp_shortage',
            'severity': 'high' if shortfall > 3 else 'medium',
            'detail':   (
                f'Only {t2_affordable} T2 ports affordable with current facilities '
                f'({total_slots} slots available). '
                f'Add more CP-generating support facilities to unlock the remaining {shortfall}.'
            ),
        })

    # Green CP bottleneck for T3
    if t3_affordable == 0 and state.green_generated < _t3_green_cost(0):
        bottlenecks.append({
            'type':     'green_cp_shortage',
            'severity': 'medium',
            'detail':   (
                f'Insufficient green CP for T3 port '
                f'(need {_t3_green_cost(0)} green, have {state.green_generated}). '
                'Add HighTech or specific support facilities to generate green CP.'
            ),
        })

    # Opportunities
    if has_ringed_body and orbital_slots > 0:
        opportunities.append({
            'type':   'ringed_anchor',
            'detail': 'Ringed body available — Asteroid Base placement possible (Extraction economy bonus).',
        })
    if t3_affordable > 0:
        opportunities.append({
            'type':   't3_viable',
            'detail': f'Budget supports {t3_affordable} T3 port(s) — consider T3 for primary economy anchor.',
        })

    # Bottleneck score (0–100): higher = more CP-constrained
    if total_slots == 0:
        cp_bottleneck_score = 100.0
    elif t2_affordable >= total_slots:
        cp_bottleneck_score = max(0.0, 30.0 - (state.yellow_available / max(1, state.yellow_generated)) * 30)
    else:
        fill_ratio = t2_affordable / total_slots
        cp_bottleneck_score = min(100.0, (1.0 - fill_ratio) * 100.0)

    # Recommended facility order: support facilities first to build CP,
    # then ports in ascending tier order
    support_ids = [f.id for f in facilities if not f.is_port and f.yellow_cp_generated > 0]
    port_ids    = [
        f.id for f in sorted(
            [f for f in facilities if f.is_port],
            key=lambda x: (x.tier, x.id)
        )
    ]
    recommended_order = support_ids + port_ids

    return CPAnalysis(
        yellow_generated=state.yellow_generated,
        green_generated=state.green_generated,
        max_t2_ports_affordable=t2_affordable,
        max_t3_ports_affordable=t3_affordable,
        cp_bottleneck_score=round(cp_bottleneck_score, 1),
        bottlenecks=bottlenecks,
        opportunities=opportunities,
        recommended_facility_order=recommended_order,
    )


def complexity_label(
    cp_bottleneck_score: float,
    slot_exhaustion_risk: float,
    build_order_sensitivity: float,
    t3_ports: int,
) -> str:
    """
    Assign a human-readable build complexity label.

    Inputs are 0–100 scores; higher = more complex.
    """
    # T3 ports immediately push to at least advanced
    if t3_ports > 0:
        composite = max(65.0, (cp_bottleneck_score + slot_exhaustion_risk + build_order_sensitivity) / 3)
    else:
        composite = (cp_bottleneck_score + slot_exhaustion_risk + build_order_sensitivity) / 3

    for threshold, label in _COMPLEXITY_THRESHOLDS:
        if composite >= threshold:
            return label
    return 'trivial'


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def port_cp_cost(tier: int, paid_port_index: int) -> tuple[int, int]:
    """
    Return the escalating CP cost for a paid port placement.

    paid_port_index is zero-based within the port tier. Primary-port
    exemptions should be handled by the caller by skipping this cost.
    """
    if tier == 3:
        return _t3_yellow_cost(paid_port_index), _t3_green_cost(paid_port_index)
    if tier == 2:
        return _t2_yellow_cost(paid_port_index), _t2_green_cost(paid_port_index)
    return 0, 0

def _t2_yellow_cost(n: int) -> int:
    """Yellow CP cost of the (n+1)th T2 port (0-indexed)."""
    if n < len(_T2_PORT_COSTS_YELLOW):
        return _T2_PORT_COSTS_YELLOW[n]
    # Beyond table: extrapolate linearly
    return _T2_PORT_COSTS_YELLOW[-1] + (n - len(_T2_PORT_COSTS_YELLOW) + 1) * T2_YELLOW_EXTRAPOLATION_STEP

def _t2_green_cost(n: int) -> int:
    if n < len(_T2_PORT_COSTS_GREEN):
        return _T2_PORT_COSTS_GREEN[n]
    return _T2_PORT_COSTS_GREEN[-1] + (n - len(_T2_PORT_COSTS_GREEN) + 1) * T2_GREEN_EXTRAPOLATION_STEP

def _t3_yellow_cost(n: int) -> int:
    if n < len(_T3_PORT_COSTS_YELLOW):
        return _T3_PORT_COSTS_YELLOW[n]
    return _T3_PORT_COSTS_YELLOW[-1] + (n - len(_T3_PORT_COSTS_YELLOW) + 1) * T3_YELLOW_EXTRAPOLATION_STEP

def _t3_green_cost(n: int) -> int:
    if n < len(_T3_PORT_COSTS_GREEN):
        return _T3_PORT_COSTS_GREEN[n]
    return _T3_PORT_COSTS_GREEN[-1] + (n - len(_T3_PORT_COSTS_GREEN) + 1) * T3_GREEN_EXTRAPOLATION_STEP


class _DummyFacility:
    """Minimal facility-like object for cost simulation."""
    def __init__(self, tier: int):
        self.tier       = tier
        self.id         = f'_sim_t{tier}'
        self.is_port    = True
        self.yellow_cp_cost = 0
        self.green_cp_cost  = 0

def _dummy_t2_port() -> '_DummyFacility':
    return _DummyFacility(2)

def _dummy_t3_port() -> '_DummyFacility':
    return _DummyFacility(3)
